# 01 - ESCI Shopping Queries Dataset Exploration

Exploration of the Amazon ESCI (Exact, Substitute, Complement, Irrelevant) Shopping Queries dataset for PRISM.
The dataset has three tables: **sources** (query origin), **products** (catalogue) and **examples** (query-product relevance judgements).

## Summary of findings

**Dataset size**
- `sources`: 130,652 queries, `query_id` is unique (one row per query).
- `products`: 1,814,924 rows across three locales: US 1,215,854 (67.0%), JP 339,059 (18.7%), ES 260,011 (14.3%).
- `examples`: 2,621,288 query-product pairs (about 20 judged products per query on average). The small version has 1,118,011 pairs (about 43% of the large version).

**Label distribution (`esci_label`)**

| Label | Count | Share |
|---|---|---|
| E - Exact | 1,708,158 | 65.2% |
| S - Substitute | 574,313 | 21.9% |
| I - Irrelevant | 263,165 | 10.0% |
| C - Complement | 75,652 | 2.9% |

**Query sources**
- Five source types: `other`, `negations`, `behavioral`, `parse_pattern`, `nlqec`.

| Source        | Count  |
|---------------|-------:|
| other         | 113656 |
| negations     |   6964 |
| parse_pattern |   6083 |
| behavioral    |   3780 |
| nlqec         |    169 |

**Keys and locales**
- `product_id` is unique within the US subset (0 duplicates) but 12,152 IDs repeat in the full table, so the same ID appears in more than one locale.

**Data quality observations**
- Queries contain typos and noise (e.g. `revent 80 cfm`, `!awnmower tires without rims`, `# 10 self-seal envelopes without window`), plus many negation queries ("without ..."), which are hard for lexical matching.
- Product fields are often missing: `product_description`, `product_bullet_point`, `product_brand` and `product_color` contain many NaN values. Some products have only a title.
- Descriptions contain raw HTML (`<p>`, `<br>`, `</br>`) and HTML entities (`&#11088;`, `&amp;`), and color values are inconsistent (`As Picture`, `Color 10`, `With Heater`). These need cleaning before text embedding.
- Query metadata consistency: Validation identified 7 query_id values with inconsistent small_version values in us_examples. All 7 IDs have small_version = 2 unique values, while query is consistent (n_texts = 1) for every ID. Query ID 79706 also has 2 unique split values; the other 6 IDs have consistent splits.

---

In [3]:
import pandas as pd

In [4]:
sources = pd.read_csv("../data/shopping_queries_dataset_sources.csv")
products = pd.read_parquet("../data/shopping_queries_dataset_products.parquet")
examples = pd.read_parquet("../data/shopping_queries_dataset_examples.parquet")

In [42]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [43]:
sources.head(100)

    query_id      source
0          0       other
1          1   negations
2          2   negations
3          3   negations
4          4  behavioral
5          5   negations
6          6   negations
7          7   negations
8          8       other
9          9       other
10        10       other
11        11   negations
12        12   negations
13        13   negations
14        14   negations
15        15   negations
16        16       other
17        17       other
18        18   negations
19        19   negations
20        20   negations
21        21   negations
22        22   negations
23        23   negations
24        24       other
25        25       other
26        26   negations
27        27       other
28        28   negations
29        29   negations
30        30   negations
31        31   negations
32        32   negations
33        33   negations
34        34   negations
35        35   negations
36        36       other
37        37   negations
38        38       other
39        39   negations
40        40   negations
41        41   negations
42        42   negations
43        43       other
44        44   negations
45        45   negations
46        46       other
47        47   negations
48        48   negations
49        49   negations
50        50   negations
51        51   negations
52        52   negations
53        53   negations
54        54       other
55        55   negations
56        56   negations
57        57   negations
58        58       other
59        59   negations
60        60   negations
61        61       other
62        62   negations
63        63       other
64        64   negations
65        65       other
66        66       other
67        67   negations
68        68       other
69        69   negations
70        70   negations
71        71   negations
72        72   negations
73        73   negations
74        74   negations
75        75   negations
76        76   negations
77        77   negations
78        78   negations
79        79   negations
80        80   negations
81        81   negations
82        82   negations
83        83   negations
84        84   negations
85        85   negations
86        86   negations
87        87   negations
88        88   negations
89        89   negations
90        90   negations
91        91   negations
92        92       other
93        93   negations
94        94   negations
95        95   negations
96        96   negations
97        97   negations
98        98   negations
99        99   negations

In [44]:
sources['query_id'].is_unique

True

In [45]:
sources['source'].unique()

<ArrowStringArray>
['other', 'negations', 'behavioral', 'parse_pattern', 'nlqec']
Length: 5, dtype: str

In [46]:
sources['source'].value_counts()

source
other            113656
negations          6964
parse_pattern      6083
behavioral         3780
nlqec               169
Name: count, dtype: int64

In [47]:
sources.shape

(130652, 2)

In [48]:
products[products['product_locale'] == 'us'].head(100)

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color,product_locale
167168,B003O0MNGC,Delta BreezSignature VFB25ACH 80 CFM Exhaust Bath Fan with Humidity Sensor,NaN,"Virtually silent at less than 0.3 sones\nPrecision engineered with DC brushless motor for extended reliability\nEasily switch in and out of humidity sensing mode by toggling wall switch\nENERGY STAR qualified for efficient cost-saving operation\nPrecision engineered with DC brushless motor for extended reliability, this fan will outlast many household appliances",DELTA ELECTRONICS (AMERICAS) LTD.,White,us
167169,B00MARNO5Y,Aero Pure AP80RVLW Super Quiet 80 CFM Recessed Fan/Light Bathroom Ventilation Fan with White Trim Ring,NaN,"Super quiet 80CFM energy efficient fan virtually disappears into the ceiling leaving only a recessed light in view\nMay be installed over shower when wired to a GFCI breaker and used with a PAR30L 75W (max) CFL\nBulb not included. Accepts any of the following bulbs: 75W Max. PAR30, 14W Max. BR30 LED, or 75W Max. PAR30L (for use over tub/shower.)",Aero Pure,White,us
167170,B011RX6PNO,"Aero Pure AP120H-SL W Slim Fit 120 CFM Bathroom Fan with LED Light and Humidity Sensor, White Finish",NaN,"Slim Fit Housing Fits Into 2"" X 6"" Ceiling Joists Or Greater\nCountry of Origin: China\nBrand name: Aero Pure\nItem Dimensions: 11. 38""L x 10. 5""W x 5. 88""H",Aero Pure,White Finish,us
167171,B01MZIK0PI,"Delta Electronics (Americas) Ltd. RAD80 Delta BreezRadiance Series 80 CFM Fan with Heater, 10.5W, 1.5 Sones",NaN,"Quiet operation at 1.5 Sones\nPrecision engineered with DC brushless motor for extended reliability, this Fan will outlast many household appliances\nGalvanized steel construction resists corrosion, equipped with metal duct adapter\nFan impeller Stops If obstructed, for safe worry-free operation\nPeace of mind quality, performance and reliability from the world's largest DC brushless Fan Manufacturer",DELTA ELECTRONICS (AMERICAS) LTD.,With Heater,us
167172,B01N5Y6002,"Delta Electronics (Americas) Ltd. GBR80HLED Delta BreezGreenBuilder Series 80 CFM Fan/Dimmable H, LED Light, Dual Speed & Humidity Sensor",NaN,"Ultra energy-efficient LED module (11-watt equivalent to 60-watt incandescent light) included. Main light output-850 Lumens, 3000K\nExtracts air at a rate of 80 CFM to properly ventilate bathrooms up to 80 sq. Ft., quiet operation at 0.8 sones\nPrecision engineered with DC brushless motor for extended reliability, this Fan will outlast many household appliances\nEnergy Star qualified for efficient cost-saving operation, galvanized steel construction resists corrosion\nFan impeller Stops If obstructed, for safe worry-free operation, attractive grille gives your bathroom a fresh look",DELTA ELECTRONICS (AMERICAS) LTD.,"With LED Light, Dual Speed & Humidity Sensor",us
167173,B07JY1PQNT,"Aero Pure ABF80 L5 W ABF80L5 Ceiling Mount 80 CFM w/LED Light/Nightlight, Energy Star Certified, White Quiet Bathroom Ventilation Fan",NaN,"Quiet 0.3 Sones, 80 CFM fan with choice of three designer grilles in White, Satin Nickel, or Oil Rubbed Bronze; Full 6 year warranty\n10W 3000K 800 Lumens LED Light with 0.7W Nightlight included\nInstallation friendly- Quick-mount adjustable metal bracket for new construction and retrofit; 4”, 5: and 6” metal duct adaptor included\nMeets today’s demanding building specifications- ETL Listed for wet application, ENERGY STAR certified, CALGreen, JA-8 Compliant for CA Title 24, and ASHRAE 62.2 compliant\nHousing dimensions- 10 2/5”x10 2/5”x 7 ½”; Grille dimensions- 13”x13”; Fits 2""x8"" joists",Aero Pure,White,us
167174,B07QJ7WYFQ,Panasonic FV-08VRE2 Ventilation Fan with Recessed LED (Renewed),NaN,"The design solution for Fan/light combinations\nEnergy Star rated architectural grade recessed Fan/LED light\nQuiet, energy efficient and powerful 80 CFM ventilation hidden above the Ceiling\nLED lamp is dimmable\nBeautiful Lighting with 6-1/2”aperture and advanced luminaire design",Panasonic,White,us
167175,B07RH6Z8KW,Delta Electronics RAD80L BreezRadiance 80 CFM Heater/Fan/Light Combo White (Renewed),"This pre-owned or refurbished product has been professionally inspected and tested to work and look like new. How a product becomes part of Amazon Renewed, your destination for pre-owned, refurbished products: A customer buys a new product and returns it or trades it in for a newer or different model. That product is inspected and tested to work and look like new by Amazon-qualified suppliers. Then, the product is sold as an Amazon Renewed product on Amazon. If not satisfied with the purchase, renewed products are eligible for replacement or refund under the Amazon Renewed Guarantee.","Quiet operation at 1.5 sones\nBuilt-in thermostat regulates temperature. Energy efficiency at 7.6 CFM/Watt\nPrecision engineered with DC brushless motor for extended reliability, this fan will outlast many household appliances\nGalvanized steel construction resists corrosion\nDuct: Detachable 4-inch Plastic Duct Adapter",DELTA ELECTRONICS (AMERICAS) LTD.,White,us
167176,B07WDM7MQQ,"Homewerks 7140-80 Bathroom Fan Ceiling Mount Exhaust Ventilation, 1.5 Sones, 80 CFM, White",NaN,"OUTSTANDING PERFORMANCE: This Homewerk's bath fan ensures comfort in your home by quietly eliminating moisture and humidity in the bathroom. This exhaust fan is 1. 5 sone at 110 CFM which means it’s able to manage spaces up to 110 square feet\nBATH FANS HELPS REMOVE HARSH ODOR: When cleaning the bathroom or toilet, harsh chemicals are used and they can leave an obnoxious odor behind. Homewerk’s bathroom fans can help remove this odor with its powerful ventilation\nBUILD QUALITY: Designed to be corrosion resistant with its galvanized steel construction featuring a grille modern style.\nEASY INSTALLATION: This exhaust bath fan is easy to install with its no-cut design and ceiling mount ventilation. Ceiling Opening (L) 7-1/2 in x Ceiling Opening (W) 7-1/4 x Ceiling Opening (H) 5-3/4 in and a 4"" round duct connector.\nHOMEWERKS TRUSTED QUALITY: Be confident in the quality and construction of each and every one of our products. We ensure that all of our products are produced and certified to regional, national and international industry standards. We are proud of the products we sell, you will be too. 3 Year Limited",Homewerks,White,us
167177,B0188A3QRM,"Amazon Basics Woodcased #2 Pencils, Unsharpened, HB Lead - Box of 144, Bulk Box",NaN,"144 woodcase #2 HB pencils made from high-quality wood for clean, easy sharpening\nStrong medium-soft lead produces long-lasting, smooth, readable strokes\nRounded hexagonal shape with satin-smooth finish for a secure, comfortable grip\nSoft, smudge-free, latex-free eraser secured to the end for conveniently wiping away mistakes",Amazon Basics,Yellow,us
167178,B075VXJ9VG,"BAZIC Pencil #2 HB Pencils, Latex Free Eraser, Wood Free Yellow Unsharpened Pencils for Exam School Office (12/Pack), 1-Pack","<p><strong>BACK TO BAZIC</strong></p><p>Our goal is to provide each customer with long-lasting supplies at an affordable cost. Since 1998, we’ve delivered on this promise and will only continue to improve every year. We’ve built our brand on integrity and quality, so customers know exactly what to expect.</p> <p><strong>COMMITTED TO VALUES</strong></p><p>We are a value-driven company, guided by the principles of excellence through strong product design at low cost. Our commitment to these values is reflected in our dedication to improving current products and developing new exciting products for our consumers.</p> <p><strong>FOCUSED ON OUR MISSION</strong></p><p>Our currency is ideas. We thrive on imagination, passion and leadership. We have great products and will to continue to rise with our customer expectations.</p> <p><strong>SUCCESS BASED ON SATISFACTION</strong></p><p>Each and every product we send out, we expect our 100% customer satisfaction. While our supplies are sourced from all across the world, our success stems from individual consumer fulfillment. We create products that people want to recommend to others.</p>","&#11088; UN-SHARPENED #2 PREMIUM PENCILS. Each pack comes with 12 un-sharpened pencils. Unlike most others out there, these allow kids the simple joy of sharpening a brand new pencil for the very 1st time!\n&#11088; CLASSIC BARREL. Made from premium-quality wood pencil is bonded with a break-resistant number two core for smooth writing as easily erased. Hexagonal shape prevents rolling and comfortable to hold.\n&#11088; QUALITY. Pencils are #2 HB for general writing, drawing and sketching. Pencils glide smoothly over paper and is highly break resistant. Pencils include a smudge-resistant eraser top for convenience.\n&#11088; LATEX-FREE ERASER. The smudge-less eraser is latex-free, which provides enough toughness for heavy erasures. These smudge-free erasers wipe the page clean, making corrections easy and fast.\n&#11088; WIDE APPLICATION. Suitable for all general writing applications such as notes, letters, and you can use it for office, classroom, home and other occasions.",BAZIC Products,12-count,us
167179,B07G7F6JZ6,"Emraw Pre Sharpened Round Primary Size No 2 Jumbo Pencils for Preschoolers, Elementary Kids - Pack of 8 Premium Fat Pencils","<p><b>Emraw Pre-Sharpened #2 HB Wood Pencils - Pack of 8 Pre-Schoolers Pencils</b></p><p>Looking for pencils for kid, office or every day general purpose repetitive use? Tired of pencils that do not sharpen well? Disappointed having broken leads repeatedly? Or, looking for pencils that require less sharpening and lasts longer?</p><p>Search no further, Emraw num 2 jumbo pencils pack have you covered. You just found the best deal. You will love them. Just the right size for pre-kindergarten toddlers. Perfect for elderly hands having difficulty grasping smaller items. Each pencil is pre-sharpened so you can literally pick straight from the box and start using. HB (no2) hardness grading with thicker leads make them perfect for most types of writing or sketching.</p><p>Made of high quality non-toxic cedar wood so they sharpen nicely with any quality dual-holed hand sharpener or adjustable electric sharpener, (not compatible with standard pencil sharpener). Rounded circular shape offers an effortless, fatigue-free writing experience.</p><p>Big ultra-smooth graphite core does not break easily, helps kids to grip securely, write smoothly and build language and motor skills. Applying normal pressure kids can wipe away mistaken strokes without a lot of effort. The soft, non-smudge rubbers are effective to erase completely and will not leave any pink residue behind after erasing unwanted marks. The eraser on top is held strongly with a ferrule and will not loosen easily, that keeps an eraser always in hand throughout its lifespan.</p><p>Use or gift these pencils to use in the classroom, work, or home for anything from keeping lists, making notes, sketch first drafts, brainstorm campaign ideas, filling in answers on an exam, coloring books as a highlighter, quick sketches of diy carpentry projects, solving sudoku or crossword puzzles.</p><p><b>Best N.2 Woodcase Pencils Supplies for You, Your Children, Students, Family, or Workmates, Order Now!!!</b></p>","✓ PACK OF 8 NUMBER 2 PRESHARPENED BEGINNERS PENCILS: Emraw round sharpened pencils set contains 2 packs of 4 general no.2 hb pencils with latex-free rubber erasers top, total 8 primary size yellow preschool pencils, good for little hands\n✓ SUPERIOR NATURAL GRIP AND FEEL: Rounded triangular wooden casing blends ergonomic design for kids small hands in mind that allows your beginner writer a firm grip to comfortably hold and practice to write, scribble or tracing for hours\n✓ CLASSIC YELLOW BARREL WOOD-CASED PENCILS: Premium pencils made from high-quality wood for easy clean sharpening, 3.25 mm thick break-resistant graphite lead requires less sharpening, produces dark long-lasting, readable, consistent strokes\n✓ EASILY ERASABLE - MAKES DO-OVERS A BREEZE: Unwanted marks are easy to erase, offers clean corrections without tearing the paper. Soft, non-smudge rubbers are effective to erase marks completely and will not leave any residue behind\n✓ VERSATILE WIDE APPLICATION: Suitable for kids, boys girls, teens, adults. Perfect for students in kindergarten school exam or college, teacher in classroom and general use: workshops, corporate office, meeting, sketching, writing, drawing",Emraw,Yellow,us
167180,B07MGKC3DD,"BIC Evolution Cased Pencil, #2 Lead, Gray Barrel, 24-Count (PGEBP241-BLK)",NaN,"Premium #2 HB lead pencils with break-resistant lead and splinter-free barrels\nDurable, long-lasting leads and erasers\nLatex-free erasers easily erase stray marks\nTrendy and modern gray barrels\nPack of 24 certified non-toxic pencils ideal for home or classroom",Design House,Gray,us
167181,B07NH2D2CP,"Maped Essentials Triangular Graphite #2 Pencils, Pack of 12 (851779ZT)",NaN,"Classic Yellow #2 Graphite Pencils with a modern twist!\nHigh quality #2 / HB Graphite is break resistant & goes down smooth!\nTriangular shape is more comfortable to hold and easier to use than a standard pencil, will not roll and is recommended by teachers!\nSharpen easily in any standard pencil sharpener\nCustomer will receive 12 pre-sharpened Graphite Pencils",Maped Helix USA,Yellow,us
167182,B07Z78H162,"BIC Xtra Fun Cased Pencil, 2 Lead, Assorted Barrel Colors, 48-Count",NaN,"Kid-friendly pencils feature bright two-toned colored barrels to make writing fun\nSmooth, break-resistant #2 lead pencils are ideal for standardized tests\nSharpens first time, every time\nLong-lasting leads and easy-to-erase, latex-free erasers\nPMA certified and non-toxic, great pencils for the classroom",BIC,NaN,us
167183,B084Q4R7SG,Holographic Pencils with Erasers Metallic Assorted Colors Wooden Glitter Pencils Optical Illusion Pencils HB Pencils (36 Pieces),"<br>36 Pieces holographic pencils <br>Enough quantity for you to use, replace and share with your families, friends and classmates. <br> <br>Shiny look: <br>These metallic wooden pencils would be glittering under the light, they are interesting enough to invite attention of boys and girls. <br> <br>Nice gifts: <br>Boys and girls may like these pencils with eraser as their gifts on birthday, Christmas, Easter and Children's Day, etc. <br> <br>Specifications: <br>Material: wood <br>Color: silver, gold, blue, purple and pink <br>Size: about 7.3 inch/ 18.5 cm in length <br> <br>Package includes: <br>36 x Holographic pencils <br> <br>Note: <br>Erasers are small parts topping on pencils, please keep them away from children under 3 years old.","5 Colors: there are 36 pieces holographic pencils with erasers in different solid colors including silver, gold, blue, purple and pink, enough quantity to use, replace and share with friends and students; Please note that pencils are not pre-sharpened\nGlitter under the light: these wooden pencils are painted with metallic colors, they would reach a shiny effect under the light, resembling magic pencils\nBring fun to life: interesting stationery to stimulate the curiosity of boys and girls, promoting them to gain related knowledge, but please keep them away from children under 3 years old\nComfortable to grip: these metallic pencils with eraser toppers are made of wood, each of them is approx. 7.3 inch/ 18.5 cm in length, proper size for adults, boys and girls to use\nGood gifts: these wooden holographic pencils are nice gifts to boys and girls on birthday, Easter, Children's Day and so on, good prizes for various competition in school",Outus,NaN,us
167184,B087J9MBXJ,YOTINO Pre-sharpened Wood Cased #2 HB Pencils - Box of 100,"</br>YOTINO Pre-sharpened #2 HB Pencils Pack of 100 </br> </br>Description </br>These HB pencils in bulk are perfect for restocking the writing materials in your office or classroom. Plus, if you’re an artist who frequently sketches, these are great to have. </br> </br>Whether you’re taking notes, making unique artwork, or sketching out a custom design, this is the best choice for premium quality pencils. </br> </br> </br>Feature: </br>Break-Resistant </br> The dense graphite cores make these pencils ideal for drawing, writing & sketching </br> </br>Durable Latex-Free Erasers </br>Will erase your marks without damaging your paper </br> </br>Sharpened & Ready-to-Use </br>Each pencil comes pre-sharpened, You can start writing, drawing, or sketching as soon as you open the box. </br> </br>Convenient Bulk Pack </br>You’ll always have enough pencils for your office, classroom or home . </br> </br>Package Includes: </br>Pre-sharpened Wood Cased Pencils - Box of 100","Convenient Bulk Pack - Box of 100 count #2 HB yellow, wood-cased pencils with latex-free eraser - certified non-toxic. Bulk pack, Smooth write for Exams, School, Office.\nBreak-Resistant - The classic design features soft #2 lead and the break-resistant lead writes smoothly and cleanly . ideal for drawing, writing & sketching.\npre-sharpened - This set of writing utensils come pre-sharpened and ready to use immediately. They feature break-resistant cores to ensure easy and even sharpening. The hard lead core will not smear nor smudge, and are ideal for scantron tests and rough drafts.\nWith Latex Free Erasers: Soft, smudge-free, latex-free eraser secured to the end for conveniently wiping away mistakes\ncomfortable grip - Each pencil is finished in a satin matte coating, giving them a comfortable grip. These writing instruments are hexagonal in shape to ensure a comfortable grip when writing, scribbling, or doodling.",N2,Yellow,us
167185,B0891R2YFN,"Wood-Cased #2 HB Pencils, Shuttle Art 600 Pack Sharpened Yellow Pencils with Erasers, Bulk Pack Graphite Pencils for School and Teacher Supplies, Writhing, Drawing and Sketching",NaN,"600 COUNT VALUE PACK: Shuttle Art 600 Pack #2 HB wood-cased yellow pencils in bulk are ideal choice for school, office and home to maintain daily pencil consumption. They are widely used in daily writhing, sketching, examination, marking, and more, especially for kids and teen writing in classroom and home.\nPRE-SHARPENED & EASY SHARPENING: All the 600 count pencils are pre-sharpened, ready to use when get it, saving your time of preparing. They are also easy to be sharpened—premium quality wood protecting the lead well and sharpens easily.\nSMOOTH WRITING & BREAK RESISTANT: Standard #2 HB pencils are durable enough for daily use. They write smoothly with bold clear marks, no smudging, and can be wiped easily. Strong, break-resistant lead guarantee long time writing and sketching, and each pencil can be fully used, no wasting at all.\nLATEX FREE PINK END ERASERS: Each pencil comes with a soft pink eraser in the end, convenient for you to wipe pencil marks at any time. No smudging or tearing paper, erase clearly and easily, and durable enough for a long time use. Conforms to ASTM-D4236, non-toxic and acid-free, safe for kids and adults.\nSERVICE GUARANTEE: Your satisfaction is our top priority, please rest assured to purchase our products. If you are not satisfied with our products or have any questions, please feel free to contact us at any time.",Shuttle Art,Yellow,us

In [49]:
examples[examples['product_locale'] == 'us'].head(100)

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train
1,1,revent 80 cfm,0,B07X3Y6B1V,us,E,0,1,train
2,2,revent 80 cfm,0,B07WDM7MQQ,us,E,0,1,train
3,3,revent 80 cfm,0,B07RH6Z8KW,us,E,0,1,train
4,4,revent 80 cfm,0,B07QJ7WYFQ,us,E,0,1,train
5,5,revent 80 cfm,0,B076Q7V5WX,us,E,0,1,train
6,6,revent 80 cfm,0,B075ZBF9HG,us,E,0,1,train
7,7,revent 80 cfm,0,B06W2LB17J,us,E,0,1,train
8,8,revent 80 cfm,0,B07JY1PQNT,us,E,0,1,train
9,9,revent 80 cfm,0,B01MZIK0PI,us,E,0,1,train
10,10,revent 80 cfm,0,B011RX6PNO,us,I,0,1,train
11,11,revent 80 cfm,0,B00XBZFWWM,us,E,0,1,train
12,12,revent 80 cfm,0,B00MARNO5Y,us,E,0,1,train
13,13,revent 80 cfm,0,B003O0MNGC,us,E,0,1,train
14,14,revent 80 cfm,0,B001E6DMKY,us,E,0,1,train
15,15,revent 80 cfm,0,B01N5Y6002,us,E,0,1,train
16,16,!awnmower tires without rims,1,B075SCHMPY,us,I,1,1,train
17,17,!awnmower tires without rims,1,B08L3B9B9P,us,E,1,1,train
18,18,!awnmower tires without rims,1,B082K7V2GZ,us,I,1,1,train
19,19,!awnmower tires without rims,1,B07P4CF3DP,us,S,1,1,train
20,20,!awnmower tires without rims,1,B07C1WZG12,us,E,1,1,train
21,21,!awnmower tires without rims,1,B077QMNXTS,us,E,1,1,train
22,22,!awnmower tires without rims,1,B01M3SJ699,us,C,1,1,train
23,23,!awnmower tires without rims,1,B06XX6BM2R,us,E,1,1,train
24,24,!awnmower tires without rims,1,B01DBGLLUC,us,S,1,1,train
25,25,!awnmower tires without rims,1,B00N16T5D8,us,I,1,1,train
26,26,!awnmower tires without rims,1,B0089RNSNM,us,E,1,1,train
27,27,!awnmower tires without rims,1,B0089RA0HY,us,S,1,1,train
28,28,!awnmower tires without rims,1,B005O5Y3QI,us,E,1,1,train
29,29,!awnmower tires without rims,1,B0018TWDOI,us,E,1,1,train
30,30,!awnmower tires without rims,1,B00004RA3F,us,I,1,1,train
31,31,!awnmower tires without rims,1,B01H3KC5U2,us,I,1,1,train
32,32,!qscreen fence without holes,2,B07D7TBSGH,us,I,1,1,test
33,33,!qscreen fence without holes,2,B07DHT2WZK,us,I,1,1,test
34,34,!qscreen fence without holes,2,B07DHX8YH2,us,E,1,1,test
35,35,!qscreen fence without holes,2,B07DS1YCRZ,us,S,1,1,test
36,36,!qscreen fence without holes,2,B07DS3J3MB,us,S,1,1,test
37,37,!qscreen fence without holes,2,B07L41H13T,us,I,1,1,test
38,38,!qscreen fence without holes,2,B07L6W8HBL,us,I,1,1,test
39,39,!qscreen fence without holes,2,B07MFP4PPQ,us,E,1,1,test
40,40,!qscreen fence without holes,2,B07S7LGN9S,us,I,1,1,test
41,41,!qscreen fence without holes,2,B07R3TNQDM,us,E,1,1,test
42,42,!qscreen fence without holes,2,B07R6P8TK8,us,E,1,1,test
43,43,!qscreen fence without holes,2,B07TVHBMZS,us,I,1,1,test
44,44,!qscreen fence without holes,2,B07XG17SPY,us,I,1,1,test
45,45,!qscreen fence without holes,2,B08NG85RHL,us,E,1,1,test
46,46,!qscreen fence without holes,2,B08TBSXMTF,us,I,1,1,test
47,47,!qscreen fence without holes,2,B0948KVQW3,us,I,1,1,test
48,48,!qscreen fence without holes,2,B078TL7LJ2,us,I,1,1,test
49,49,!qscreen fence without holes,2,B07QC4X29H,us,I,1,1,test
50,50,!qscreen fence without holes,2,B078RHZTVK,us,I,1,1,test
51,51,!qscreen fence without holes,2,B01EYHHO2G,us,E,1,1,test
52,52,!qscreen fence without holes,2,B072M34RQC,us,I,1,1,test
53,53,!qscreen fence without holes,2,B077Z8Z8D8,us,E,1,1,test
54,54,!qscreen fence without holes,2,B000HMCA7W,us,I,1,1,test
55,55,!qscreen fence without holes,2,B0019Y6TTC,us,E,1,1,test
56,56,!qscreen fence without holes,2,B001OJXVKW,us,E,1,1,test
57,57,!qscreen fence without holes,2,B0030E1WLE,us,I,1,1,test
58,58,!qscreen fence without holes,2,B003VNKLIY,us,I,1,1,test
59,59,!qscreen fence without holes,2,B0079GH86C,us,I,1,1,test
60,60,!qscreen fence without holes,2,B00JNTYX3Y,us,I,1,1,test
61,61,!qscreen fence without holes,2,B0079GH6J6,us,C,1,1,test
62,62,!qscreen fence without holes,2,B018JYCD80,us,E,1,1,test
63,63,!qscreen fence without holes,2,B018JYCD9Y,us,S,1,1,test
64,64,!qscreen fence without holes,2,B01ESSA9VO,us,I,1,1,test
65,65,!qscreen fence without holes,2,B01JLK7L56,us,I,1,1,test
66,66,!qscreen fence without holes,2,B01N4AMZ8Y,us,S,1,1,test
67,67,!qscreen fence without holes,2,B06XTWZ857,us,I,1,1,test
68,68,!qscreen fence without holes,2,B071HW515B,us,I,1,1,test
69,69,!qscreen fence without holes,2,B018JYCBWI,us,I,1,1,test
149,149,# 10 self-seal envelopes without window,5,B07RP3F2LW,us,E,1,1,train
150,150,# 10 self-seal envelopes without window,5,B07FK9PCZB,us,E,1,1,train
151,151,# 10 self-seal envelopes without window,5,B07FMDV5LR,us,S,1,1,train
152,152,# 10 self-seal envelopes without window,5,B07GJCSF8Z,us,E,1,1,train
153,153,# 10 self-seal envelopes without window,5,B07GJKFC5X,us,E,1,1,train
154,154,# 10 self-seal envelopes without window,5,B07M7V7TBW,us,S,1,1,train
155,155,# 10 self-seal envelopes without window,5,B07NZ4T2SL,us,I,1,1,train
156,156,# 10 self-seal envelopes without window,5,B07RP467JB,us,E,1,1,train
157,157,# 10 self-seal envelopes without window,5,B078S5ZL5D,us,E,1,1,train
158,158,# 10 self-seal envelopes without window,5,B085VV4TV5,us,S,1,1,train
159,159,# 10 self-seal envelopes without window,5,B085WJMWC9,us,E,1,1,train
160,160,# 10 self-seal envelopes without window,5,B08G14MTVW,us,E,1,1,train
161,161,# 10 self-seal envelopes without window,5,B08V344BCQ,us,E,1,1,train
162,162,# 10 self-seal envelopes without window,5,B08WN3K65B,us,S,1,1,train
163,163,# 10 self-seal envelopes without window,5,B08Y8TWR38,us,S,1,1,train
164,164,# 10 self-seal envelopes without window,5,B08Y8VX63W,us,I,1,1,train
165,165,# 10 self-seal envelopes without window,5,B08Y97TG79,us,I,1,1,train
166,166,# 10 self-seal envelopes without window,5,B07VYKJSZS,us,E,1,1,train
167,167,# 10 self-seal envelopes without window,5,B07566JS34,us,I,1,1,train
168,168,# 10 self-seal envelopes without window,5,B07CXXVXLC,us,E,1,1,train
169,169,# 10 self-seal envelopes without window,5,B074M9FN2P,us,E,1,1,train
170,170,# 10 self-seal envelopes without window,5,B002R5ARDG,us,E,1,1,train
171,171,# 10 self-seal envelopes without window,5,B007YX2KB8,us,E,1,1,train
172,172,# 10 self-seal envelopes without window,5,B008005REQ,us,E,1,1,train
173,173,# 10 self-seal envelopes without window,5,B00OS9Q292,us,S,1,1,train
174,174,# 10 self-seal envelopes without window,5,B00V5DGIL6,us,E,1,1,train
175,175,# 10 self-seal envelopes without window,5,B00WKZ559Y,us,I,1,1,train
176,176,# 10 self-seal envelopes without window,5,B016V06OYS,us,E,1,1,train
177,177,# 10 self-seal envelopes without window,5,B01C67JZ50,us,E,1,1,train
178,178,# 10 self-seal envelopes without window,5,B01D0OANU4,us,E,1,1,train

In [50]:
products['product_locale'].unique()

<ArrowStringArray>
['es', 'us', 'jp']
Length: 3, dtype: str

In [51]:
products[products['product_locale'] == 'us'].shape

(1215854, 7)

In [52]:
products.shape

(1814924, 7)

In [53]:
examples[
    examples["product_locale"] == "us"
].head(100)

,example_id,query,query_id,product_id,product_locale,esci_label,small_version,large_version,split
0,0,revent 80 cfm,0,B000MOO21W,us,I,0,1,train
1,1,revent 80 cfm,0,B07X3Y6B1V,us,E,0,1,train
2,2,revent 80 cfm,0,B07WDM7MQQ,us,E,0,1,train
3,3,revent 80 cfm,0,B07RH6Z8KW,us,E,0,1,train
4,4,revent 80 cfm,0,B07QJ7WYFQ,us,E,0,1,train
5,5,revent 80 cfm,0,B076Q7V5WX,us,E,0,1,train
6,6,revent 80 cfm,0,B075ZBF9HG,us,E,0,1,train
7,7,revent 80 cfm,0,B06W2LB17J,us,E,0,1,train
8,8,revent 80 cfm,0,B07JY1PQNT,us,E,0,1,train
9,9,revent 80 cfm,0,B01MZIK0PI,us,E,0,1,train
10,10,revent 80 cfm,0,B011RX6PNO,us,I,0,1,train
11,11,revent 80 cfm,0,B00XBZFWWM,us,E,0,1,train
12,12,revent 80 cfm,0,B00MARNO5Y,us,E,0,1,train
13,13,revent 80 cfm,0,B003O0MNGC,us,E,0,1,train
14,14,revent 80 cfm,0,B001E6DMKY,us,E,0,1,train
15,15,revent 80 cfm,0,B01N5Y6002,us,E,0,1,train
16,16,!awnmower tires without rims,1,B075SCHMPY,us,I,1,1,train
17,17,!awnmower tires without rims,1,B08L3B9B9P,us,E,1,1,train
18,18,!awnmower tires without rims,1,B082K7V2GZ,us,I,1,1,train
19,19,!awnmower tires without rims,1,B07P4CF3DP,us,S,1,1,train
20,20,!awnmower tires without rims,1,B07C1WZG12,us,E,1,1,train
21,21,!awnmower tires without rims,1,B077QMNXTS,us,E,1,1,train
22,22,!awnmower tires without rims,1,B01M3SJ699,us,C,1,1,train
23,23,!awnmower tires without rims,1,B06XX6BM2R,us,E,1,1,train
24,24,!awnmower tires without rims,1,B01DBGLLUC,us,S,1,1,train
25,25,!awnmower tires without rims,1,B00N16T5D8,us,I,1,1,train
26,26,!awnmower tires without rims,1,B0089RNSNM,us,E,1,1,train
27,27,!awnmower tires without rims,1,B0089RA0HY,us,S,1,1,train
28,28,!awnmower tires without rims,1,B005O5Y3QI,us,E,1,1,train
29,29,!awnmower tires without rims,1,B0018TWDOI,us,E,1,1,train
30,30,!awnmower tires without rims,1,B00004RA3F,us,I,1,1,train
31,31,!awnmower tires without rims,1,B01H3KC5U2,us,I,1,1,train
32,32,!qscreen fence without holes,2,B07D7TBSGH,us,I,1,1,test
33,33,!qscreen fence without holes,2,B07DHT2WZK,us,I,1,1,test
34,34,!qscreen fence without holes,2,B07DHX8YH2,us,E,1,1,test
35,35,!qscreen fence without holes,2,B07DS1YCRZ,us,S,1,1,test
36,36,!qscreen fence without holes,2,B07DS3J3MB,us,S,1,1,test
37,37,!qscreen fence without holes,2,B07L41H13T,us,I,1,1,test
38,38,!qscreen fence without holes,2,B07L6W8HBL,us,I,1,1,test
39,39,!qscreen fence without holes,2,B07MFP4PPQ,us,E,1,1,test
40,40,!qscreen fence without holes,2,B07S7LGN9S,us,I,1,1,test
41,41,!qscreen fence without holes,2,B07R3TNQDM,us,E,1,1,test
42,42,!qscreen fence without holes,2,B07R6P8TK8,us,E,1,1,test
43,43,!qscreen fence without holes,2,B07TVHBMZS,us,I,1,1,test
44,44,!qscreen fence without holes,2,B07XG17SPY,us,I,1,1,test
45,45,!qscreen fence without holes,2,B08NG85RHL,us,E,1,1,test
46,46,!qscreen fence without holes,2,B08TBSXMTF,us,I,1,1,test
47,47,!qscreen fence without holes,2,B0948KVQW3,us,I,1,1,test
48,48,!qscreen fence without holes,2,B078TL7LJ2,us,I,1,1,test
49,49,!qscreen fence without holes,2,B07QC4X29H,us,I,1,1,test
50,50,!qscreen fence without holes,2,B078RHZTVK,us,I,1,1,test
51,51,!qscreen fence without holes,2,B01EYHHO2G,us,E,1,1,test
52,52,!qscreen fence without holes,2,B072M34RQC,us,I,1,1,test
53,53,!qscreen fence without holes,2,B077Z8Z8D8,us,E,1,1,test
54,54,!qscreen fence without holes,2,B000HMCA7W,us,I,1,1,test
55,55,!qscreen fence without holes,2,B0019Y6TTC,us,E,1,1,test
56,56,!qscreen fence without holes,2,B001OJXVKW,us,E,1,1,test
57,57,!qscreen fence without holes,2,B0030E1WLE,us,I,1,1,test
58,58,!qscreen fence without holes,2,B003VNKLIY,us,I,1,1,test
59,59,!qscreen fence without holes,2,B0079GH86C,us,I,1,1,test
60,60,!qscreen fence without holes,2,B00JNTYX3Y,us,I,1,1,test
61,61,!qscreen fence without holes,2,B0079GH6J6,us,C,1,1,test
62,62,!qscreen fence without holes,2,B018JYCD80,us,E,1,1,test
63,63,!qscreen fence without holes,2,B018JYCD9Y,us,S,1,1,test
64,64,!qscreen fence without holes,2,B01ESSA9VO,us,I,1,1,test
65,65,!qscreen fence without holes,2,B01JLK7L56,us,I,1,1,test
66,66,!qscreen fence without holes,2,B01N4AMZ8Y,us,S,1,1,test
67,67,!qscreen fence without holes,2,B06XTWZ857,us,I,1,1,test
68,68,!qscreen fence without holes,2,B071HW515B,us,I,1,1,test
69,69,!qscreen fence without holes,2,B018JYCBWI,us,I,1,1,test
149,149,# 10 self-seal envelopes without window,5,B07RP3F2LW,us,E,1,1,train
150,150,# 10 self-seal envelopes without window,5,B07FK9PCZB,us,E,1,1,train
151,151,# 10 self-seal envelopes without window,5,B07FMDV5LR,us,S,1,1,train
152,152,# 10 self-seal envelopes without window,5,B07GJCSF8Z,us,E,1,1,train
153,153,# 10 self-seal envelopes without window,5,B07GJKFC5X,us,E,1,1,train
154,154,# 10 self-seal envelopes without window,5,B07M7V7TBW,us,S,1,1,train
155,155,# 10 self-seal envelopes without window,5,B07NZ4T2SL,us,I,1,1,train
156,156,# 10 self-seal envelopes without window,5,B07RP467JB,us,E,1,1,train
157,157,# 10 self-seal envelopes without window,5,B078S5ZL5D,us,E,1,1,train
158,158,# 10 self-seal envelopes without window,5,B085VV4TV5,us,S,1,1,train
159,159,# 10 self-seal envelopes without window,5,B085WJMWC9,us,E,1,1,train
160,160,# 10 self-seal envelopes without window,5,B08G14MTVW,us,E,1,1,train
161,161,# 10 self-seal envelopes without window,5,B08V344BCQ,us,E,1,1,train
162,162,# 10 self-seal envelopes without window,5,B08WN3K65B,us,S,1,1,train
163,163,# 10 self-seal envelopes without window,5,B08Y8TWR38,us,S,1,1,train
164,164,# 10 self-seal envelopes without window,5,B08Y8VX63W,us,I,1,1,train
165,165,# 10 self-seal envelopes without window,5,B08Y97TG79,us,I,1,1,train
166,166,# 10 self-seal envelopes without window,5,B07VYKJSZS,us,E,1,1,train
167,167,# 10 self-seal envelopes without window,5,B07566JS34,us,I,1,1,train
168,168,# 10 self-seal envelopes without window,5,B07CXXVXLC,us,E,1,1,train
169,169,# 10 self-seal envelopes without window,5,B074M9FN2P,us,E,1,1,train
170,170,# 10 self-seal envelopes without window,5,B002R5ARDG,us,E,1,1,train
171,171,# 10 self-seal envelopes without window,5,B007YX2KB8,us,E,1,1,train
172,172,# 10 self-seal envelopes without window,5,B008005REQ,us,E,1,1,train
173,173,# 10 self-seal envelopes without window,5,B00OS9Q292,us,S,1,1,train
174,174,# 10 self-seal envelopes without window,5,B00V5DGIL6,us,E,1,1,train
175,175,# 10 self-seal envelopes without window,5,B00WKZ559Y,us,I,1,1,train
176,176,# 10 self-seal envelopes without window,5,B016V06OYS,us,E,1,1,train
177,177,# 10 self-seal envelopes without window,5,B01C67JZ50,us,E,1,1,train
178,178,# 10 self-seal envelopes without window,5,B01D0OANU4,us,E,1,1,train

In [54]:
examples.shape

(2621288, 9)

In [55]:
products['product_locale'].value_counts()

product_locale
us    1215854
jp     339059
es     260011
Name: count, dtype: int64

In [56]:
# is product_id unique, or does the same product repeat across locales?
products['product_id'].duplicated().sum()

np.int64(12152)

In [57]:
us_products = products[products['product_locale'] == 'us']
us_products['product_id'].duplicated().sum()

np.int64(0)

In [58]:
us_examples = examples[examples['product_locale'] == 'us']

In [59]:
# esci_label distribution
examples['esci_label'].value_counts()

esci_label
E    1708158
S     574313
I     263165
C      75652
Name: count, dtype: int64

In [60]:
# small vs large version split sizes
examples[['small_version','large_version']].sum()

small_version    1118011
large_version    2621288
dtype: int64

In [61]:
group = us_examples.groupby("query_id")
flags = group[["split", "small_version"]].nunique()
flags["n_texts"] = group["query"].nunique()
bad_ids = flags[(flags["split"] > 1) | (flags["small_version"] > 1) | (flags["n_texts"] > 1)].index

In [64]:
print(flags.loc[bad_ids].to_string())

          split  small_version  n_texts
query_id
694           1              2        1
26525         1              2        1
46791         1              2        1
79706         2              2        1
91973         1              2        1
98413         1              2        1
114163        1              2        1

In [62]:
print(len(bad_ids))

7

In [5]:
query_words = examples["query"].str.split().str.len()

query_words.describe()

count    2.621288e+06
mean     3.253567e+00
std      1.718152e+00
min      1.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      2.900000e+01
Name: query, dtype: float64

In [63]:
nlqec_ids = sources.loc[
    sources["source"] == "nlqec", "query_id"
]

nlqec_queries = examples[
    examples["query_id"].isin(nlqec_ids)
][["query_id", "query"]].drop_duplicates()

display(nlqec_queries)

,query_id,query
57831,2162,15 inch light weight laptop that has lots of memory storage and RAM. It should include a HDMI port as well as a USB drive.
133318,5608,A Lenovo like mine its a little notebook it's fab. It would be black in colour
133350,5609,A Windows laptop that I can use to play and stream games. It should have at least a 15 screen.
133366,5610,"A basic, denim jacket that has a slightly oversized fit."
133405,5611,"A bomber jacket with inner warming lining, preferrably black"
133445,5612,A laptop that had good gaming capabilities while being budget friendly
133460,5613,A laptop that is light weight and with high specifications which I could use for working when at home or when travelling.
133500,5614,A laptop which runs faster and has more capacity to run downloaded software
133516,5615,A laptop with enough power to play 4K videos and run photoshop easily.
133531,5616,A lightweight one with long battery life and quick processor with adequate storage. One that can be transported easily with at least a 13 inch screen and backlit keyboard.
133557,5617,"A lightweight, cheap laptop, Windows based, with office installed"
133573,5618,"A long (mid calf length), lightweight beige/brown single breasted trench jacket"
133613,5619,A mid-range spec laptop with a nice screen but lightweight and easy for travelling with.
133628,5620,A multi functional convertible laptop running on a Windows operating system
133644,5621,A navy blue puffer jacket which covers my bum and has a fur lined hood. It also has a gold zip & fleece lined pockets
133680,5622,A new black jacket for the spring/summer season. Tailored like a trench coat or a duster jacket.
133720,5623,A new jacket which is green in colour and lightweight
133760,5624,"A plain black, warm puffer jacket with a hood and decently sized pockets"
133800,5625,A powerful yet slim laptop which allows me to do all my normal note-taking plus a bit of light gaming on the side
133815,5626,"A second-hand or vintage mid-weight jacket, or one from a sustainable brand."
133852,5627,A short length light blue denim jacket which looks faded or worn
133892,5628,A standard laptop running on windows. It has good sound and graphics
133907,5629,"A standard new laptop that is budget friendly and which has internet access, a windows operating system, large clean screen and user friendly"
133923,5630,A three quarter length jacket in navy with a zip and two large pockets on the front
133962,5631,A warm but washable longer length jacket to protect me from the cold and rain.If possible made from sustainable materials like cotton or wool.
133998,5632,A warm jacket that feels comfy. Also probably one with plaid.
134036,5633,"A windows laptop which has a webcam, access to microsoft office and a decent graphics card. A laptop which runs very quickly and efficiently"
134052,5634,"Always go for function over fashion, look for a warm multi purpose jacket with plenty of pockets and is water proof"
134086,5635,An everyday laptop for surfing the net and emails and not too expensive.
134102,5636,Anything with high power capabilities/a gaming laptop.
134118,5637,Apple MacBook Pro with as high a spec as I could afford
134134,5638,"Big screen, lightweight, high memory, fast start up, most recent processor"
134150,5639,Black leather jacket with a removable hood insert. Similar to a biker jacket.
134189,5640,Black leather jacket with dark leopard print and black patent leather detailing.
134229,5641,"Black, padded jacket with a hood. Warm and waterproof, not too expensive."
134269,5642,"Compact, 15 inch screen minimum, thin, fast operating system and chip, reliable provenance. Windows based with latest software installed"
134284,5643,Dark blue denim jackets with a fluffy inside and collar similar to aviator jacket
134323,5644,"For a replacement laptop, I would choose an Apple macbook"
134339,5645,"Good size keyboard, large screen, detachable keyboard so it can be used as a tablet. Decent camera and webcam. Good connectivity."
134352,5646,High spec gaming laptop so that I can do 3D modelling.
134368,5647,Hooded jacket that is heavy but has material that can be worn is cool weather or cold weather. Had pockets inside and out.
134408,5648,I WANT A NEW APPLE MAC BOOK AIR TO REPLACE MINE AS IT IS THE BEST LAPTOP THAT I HAVE USED
134423,5649,I am going to buy a laptop with large memory capacity and a well known brand.
134437,5650,I am going to get a high spec laptop. From a company like Asus or a brand more known for their gaming style laptops than work-based ones.
134452,5651,"I am looking for a mid-priced laptop (max budget £400) with at least two USB ports, low weight and a slim profile."
134467,5652,I am looking for a simple plain jacket that is comfortable to wear.
134504,5653,"I am looking to purchase a black leather biker jacket, which has to be real leather"
134542,5654,I am purchasing a new laptop from the same brand that is higher specifications than my old one. I will use this chance to update my device.
134553,5655,I am seriously looking at a Apple’s MacBook Air because it is a thinner and lighter laptop
134568,5656,I choose a navy wool pea coat that is long and warm
134607,5657,"I like to buy a low-mid range laptop. One that looks good, is light to carry and have a LCD screen."
134621,5658,I need a laptop that has 16 GB of RAM. A backlit keyboard is also essential. SSD preferred. Physical blemishes that create a discount are great.
134637,5659,"I need something timeless and that can go with any outfit, not a thin fabric but not thick either because I get warm easily."
134649,5660,"I need to buy a thin, lightweat laptop, with good storage and battery life, it needs to have a webcam and charge using USBC."
134664,5661,"I really want one with a unique print, not floral or tartan but something different and colourful, really needs to be comfortable and hasn't got a hood"
134674,5662,I want a Kenneth Cole peacoat that is double padded on the inside and has minimal buttons
134712,5663,I want a black leather jacket with gold zips and pocket buttons
134751,5664,"I want a fast and powerful laptop , a macbook or a windows I don't mind but something fast and lightweight to carry."
134763,5665,"I want a google chromebook, that converts to a tablet, and it has to have a full size keyboard."
134779,5666,I want a jacket that keeps me dry and warm and preferably purple.
134817,5667,"I want a jacket without a hood that is fairly slim-fitting, but warm."
134856,5668,"I want a laptop that allows me to play some older games, surf the internet, and watch dvd's and blu-ray disks."
134893,5669,"I want a laptop that is light weight, but can handle all of my daily needs."
134908,5670,"I want a light weight chromebook, something which is easy to carry with me, It must have built in security and use google chrome as my search ."
134945,5671,"I want a lightweight, portable laptop that fits in with my other electrical products."
134961,5672,I want a long jacket that comes to mid leg in a dark colour and very warm
134997,5673,I want a replacement chrome book with a touch screen. So really it would be an upgrade. I want a large screen and a good memory
135010,5674,I want a single breasted corduroy hip length jacket with 2 side pockets
135049,5675,"I want a slightly oversized, worn, dark denim jacket, similar to Levi's style"
135087,5676,"I want a warm, waterproof coat with a hood. One that zips up. Preferably black or khaki green in colour."
135123,5677,I want the burgundy hoodie jacket with the two big center pockets
135161,5678,I want the new laptop to have a replaceable battery and to be solid state and ruggedized to deal with bumps and scrapes.
135176,5679,"I want to buy a laptop that has a lot of features, and is of good quality."
135191,5680,I want to buy a laptop that is touchscreen and has a long battery time. I also want it to be sleek and lightweight.
135205,5681,"I want to buy a powerful laptop to put linux on, so maybe a lenovo or dell with a clear screen and lightweight."
135218,5682,I want to get fancier one than the laptop I had. I think I want one of the ones with a touchscreen that folds in different ways
135250,5683,I would be looking for a laptop that is good value and lightweight with long battery life.
135289,5684,I would buy a baubax travel jacket since I love all the pockets.
135324,5685,"I would buy a long coat, like a fitted trench coat?"
135361,5686,I would buy a macbook pro. I would try to get a refurbished one but am open to other options.
135376,5687,I would buy a nice comfortable sweater. A hoodie preferably. I don't care about the appearance nearly as much as i do about comfort.
135407,5688,I would buy a simple black waterproof jacket with lots of pockets.
135442,5689,"I would buy a vintage jean jacket, with a shearling lined interior."
135478,5690,"I would buy a waterproof jacket that is also warm, even in winter. The jacket would also need to fit well and have multiple pockets."
135513,5691,I would buy an affordable warm jacket.I would buy a jacket that is on sale.
135547,5692,I would buy an apple mac book air as they are light fast and easy to use
135563,5693,I would buy the exact same laptop that I have now. I would get another Apple Macbook Air.
135576,5694,I would choose a Macbook Air as a replacement with 128GB data.
135590,5695,I would choose a blue hoodie as a replacement jacket that i would want to buy
135626,5696,I would choose a jacket that is warm but versatile with a hood. Perhaps a jacket that could be worn for multiple seasons.
135658,5697,"I would choose a jacket that was comfortable, good quality and light weight but stylish and fashionable."
135690,5698,"I would choose a laptop that has a lot of memory storage, a long battery life, a decent screen size and in a nice colour."
135704,5699,"I would choose a laptop with a good screen, large RAM, great processor, and a good video card."
135718,5700,I would choose a laptop with a solid state hard drive and that is slim and light.
135732,5701,"I would choose a lightweight slim laptop that would be touch screen. Fast intel hard drive, battery life would be long lasting"
135746,5702,I would choose a low cost entry price point basic laptop
135785,5703,I would choose a medium weight fleece jacket with a hood. I would choose a black colored jacket.
135819,5704,"I would choose a medium weight waterproof fabric, hip length jacket or longer, long sleeves, zip front, with a hood and deep pockets with zips"
135852,5705,I would choose a reasonably-priced (under $50) short trenchcoat as a replacement.
135889,5706,I would choose an ASUS laptop with a solid state hard drive and 15.6 screen.
135903,5707,"I would choose an upper end laptop with high specifcations, so that it will last for a number of years"
135937,5708,"I would choose something small and lightweight, maybe a chromebook,"
135969,5709,I would get a Windows laptop that could support online gaming. Full keyboard with num pad and a large monitor.
135982,5710,"I would just like to have a jacket with pockets, and is light and plain looking; no flashy colors."
136019,5711,"I would like a laptop with a big screen, touch screen if possible but not too expensive."
136035,5712,I would like a light weight jacket that is medium length with a hood and a zip fastening
136074,5713,I would like a long black asymmetrical hoodie jacket. Totally goth looking and awesome enough to wear over a dress or a pair of jeans
136110,5714,I would look for a Windows 10 laptop nearer the top end of specification. I'd prefer an SSD and at least 8Gb of RAM
136125,5715,"I would probably choose another MacBook as a replacement, probably a MacBook Air"
136160,5716,I would probably spend the heavy coin and get a gaming pc
136173,5717,"I would purchase a laptop with good processing power, a RAM of above 10GB, a good video card, and good battery power."
136189,5718,I would purchase the newest macbook pro with high storage capacity
136204,5719,I would replace it with a soft gray wool sweater. The sweater should be warm but functional in all weather. The jacket should also be fashionable.
136224,5720,"I would want a Windows laptop that is small and thin but has a ssd hard drive, 8gb ram and good graphics. I want a quick and reliable machine."
136238,5721,I would want a decently powerful laptop. With a good CPU
136254,5722,I would want a light weight protable laptop with a graphics card and alot of memory
136293,5723,I would want a my replacement to be a Camo print jacket. Since i never had a Camo print jacket me picking this out as a replacement works.
136320,5724,I would want a warm winter jacket. It would need a hood.
136358,5725,"I'd buy a Dell or HP running Windows, I need a big hard drive and lostsa memory"
136371,5726,"I'd go with a leather jacket with good protection for use on a motorcycle. Elbow/Shoulder armor is not necessary, but having back protection would be great."
136406,5727,"I'd like to get a warm jacket, maybe a hooded parka with soft nice lining (sherpa), navy, purple, burgundy or black."
136444,5728,I'm looking for a fully waterproof and windproof jacket with a padded lining a hood and ideally in dark green.
136482,5729,I'm looking for something classic with a slim cut and waterproof technology
136496,5730,I'm looking to get a marroon jacket. I'm looking for one which is water proof but not too heavy. I don't want a winter jacket.
136533,5731,It is a navy blue twill fabric and is a typical single breasted blazer style with three buttons and lapels in a deeper blue twill fabric.
136565,5732,Its a Dell laptop with15 inch touch screen with 32g ram
136580,5733,Its just a light weight everyday jacket that washes easy. It was inexpensive and so comfy
136608,5734,It’s a lightweight jacket that is water and wind resistant but has a fleece lining so it can be used in a wide variety of weather.
136645,5735,Large screen with keyboard attachment and must be capable of using design programmes
136657,5736,Like to have Google chrome on it. Must not be a notebook laptop. Like lots of memory. Latest running systems on it
136687,5737,Long black parka jacket Insulated with warm artificial filling and waterproofed for all weather with hood and multiple pockets
136726,5738,MacBook in all white with a lot of memory and a wireless mouse
136742,5739,"Macbook Pro, silver, simple, with long charger lead."
136758,5740,Macbook or any apple product because I have an iPhone and iPad and all my work syncs
136789,5742,"My new laptop would be silver, have the best storage I can afford (hard drive) and be able to burn CDs. My current laptop does not have this facility."
136801,5743,Nice new top of the range laptop with maybe where the screen comes away on it's own
136814,5744,Not sure. Maybe a a standard size (15 or 17??) screen middle of the range laptop that is either black or purple. It might be a Dell or Acer
136844,5745,"One that’s fast, reliable and has a good processor. I’d ideally like it to be light-weight too so that I can easily transport it."
136871,5746,"One with an SSD drive, good RAM, fast processor, and a 15 screen, lightweight but ideally with a built in DVD/CD drive"
136887,5747,Pockets on both sides. Brown leather. Extra large.
136909,5748,"Portable, touch-screen, with a pen, high resolution display, good speakers."
136921,5749,Since I have a desktop any laptop for work with decent specifications would do
136933,5750,"Solid state drive, fast, with copious memory. Two USB ports minimum. High resolution display. Prefer 12” monitor or larger, and prefer number pad."
136947,5751,"Something casual, that i can wear out and about and to work, nothing to flashy but easy to clean. Will try and get something in the sale."
136968,5752,Something that’s lightweight to carry and can be used to surf the internet and use Microsoft Office
136995,5753,Something versatile. Like a plain black puff coat maybe. That can be worn in its own right but can easily be thrown over a hoodie or another jacket too.
137031,5754,The ideal replacement would be lightweight and slim with a high quality internal processor and sound system. It would also be reasonably priced and chrome in colour.
137039,5755,"The jacket I am planning on buying is a hoodie with high visibility reflective strips on it, for safety."
137078,5756,The jacket I would choose as a replacement is a leather jacket
137113,5757,The jacket I would try to replace with the one I wear daily is a top gun bomber jacket.
137149,5758,The laptop I would choose would be a silver apple Macbook. It would be thin and easy to carry around.
137186,5759,"The laptop I would like would be a sleek, silver Apple Macbook Pro."
137226,5760,The laptop should be a windows laptop. Light with powerful processor and good memory
137241,5761,"The replacement jacket would be waxed brown cotton, a brass zip, very waterproof and comfortable. It would be three quarter length with a detachable hood."
137276,5762,"Thin, lightweight but also waterproof and looks good. Hood not essential."
138381,5810,"a deep, blue soft denim jacket with pockets and buttons"
138989,5841,"a laptop in pink, with a high processor, plenty of memory, ram and usb ports.top of the range model"
361691,17334,"blue bomber jacket, most likely h and m or similar"
740773,36863,"either a Nike, Adidas jacket with dark colours like black with minimal extra designs on it."
1037007,52353,i am looking for an olive green fur coat that has a cheetah print on it. it is a long jacket with buttons.
1039515,52479,i want a warm jacket with a hood and that is waterproof and black or dark coloured like navy
1039817,52491,i would be buying an asus laptop or another brand of similar quality.
1039873,52493,i'd get a windows laptop since i have always used them
1043869,52685,id choose a softshell jacket that i can ear a hoodie underneith
1044010,52693,"ideally something with 8gb of ram, probably a windows laptop around £400 as in my experience that's what you can rely on and macs are too expensive."
1431138,72705,"need a nice warm but cheap and washable new jacket,hoping for a nice colour blue purple or red"
1431178,72706,"need a small neat affordable netbook or small laptop to do emails and internet ,nothing fancy."
1456755,74085,no need for a cd drive but a high speed ssd with lots of ram and a 15 inch display
1639112,83522,probably something that has a good amd ryzen processor in it with metal build quality and a nice va panel screen