In [1]:
import pandas as pd
import re

In [2]:
shopping_queries_dataset_sources = pd.read_csv("../data/shopping_queries_dataset_sources.csv")
shopping_queries_dataset_products = pd.read_parquet("../data/shopping_queries_dataset_products.parquet")
shopping_queries_dataset_examples = pd.read_parquet("../data/shopping_queries_dataset_examples.parquet")

In [3]:
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [4]:
electronics_keywords = [
    # mobile & computing
    "phone", "smartphone", "laptop", "notebook computer", "tablet", "desktop computer",
    "smartwatch", "chromebook",
    # components
    "ram", "ddr4", "ddr5", "ssd", "hard drive", "processor", "cpu", "gpu", "motherboard",
    "power bank", "charger", "usb cable", "hdmi cable",
    # imaging
    "camera", "dash cam", "webcam", "security camera", "camcorder",
    # home electronics
    "television", " tv ", "smart speaker", "router", "wifi extender", "bluetooth speaker",
    # audio
    "headphone", "earbud", "earphone"
]

brand_allowlist = [
    "samsung", "apple", "xiaomi", "sony", "lg", "dell", "hp", "lenovo", "asus",
    "acer", "panasonic", "canon", "nikon", "gopro", "logitech", "jbl", "bose",
    "anker", "tp-link", "netgear", "corsair", "kingston", "western digital", "seagate"
]

conglomerate_brands = ['samsung', 'sony', 'lg', 'panasonic']

In [16]:
import re

title_lower = us_products['product_title'].str.lower().fillna('')
bullet_lower = us_products['product_bullet_point'].str.lower().fillna('')
brand_lower = us_products['product_brand'].str.lower().fillna('')

# --- keyword match (title only, non-capturing group to silence the warning) ---
pattern = r'\b(?:' + '|'.join(re.escape(k) for k in electronics_keywords) + r')\b'
keyword_mask = title_lower.str.contains(pattern, regex=True)

# --- brand match ---
brand_mask = brand_lower.isin(brand_allowlist)

# --- conglomerate-brand fix: brand alone isn't enough for brands that also sell
#     non-electronics goods (Samsung dryers, Sony movies/games/music, etc.) ---
conglomerate_brands = ['samsung', 'sony', 'lg', 'panasonic']

hardware_nouns = (
    r'\b(?:player|console|headphones?|speakers?|lens|camera|batter(?:y|ies)'
    r'|receiver|soundbar|walkman|radio|monitor|vcr|changer|memory card'
    r'|earbuds?|earphones?|turntable|amplifier)\b'
)
hardware_noun_mask = title_lower.str.contains(hardware_nouns, regex=True)

is_conglomerate = brand_lower.isin(conglomerate_brands)

# conglomerate brand-only matches must ALSO have a hardware noun to count;
# non-conglomerate brand matches are unaffected
brand_mask_final = brand_mask & ~(is_conglomerate & ~keyword_mask & ~hardware_noun_mask)

# --- exclusions: homonym collisions discovered across all samples so far ---
exclude_pattern = (
    r'\b(?:food processor'
    r'|dodge ram|ram \d{3,4}|ram trucks?|ram pickup|ram hitch'
    r'|dodge charger|charger challenger'
    r'|wood(?:en)? router|router table'
    r'|as seen on tv|tv show'
    r'|writing tablet|the emerald tablet)\b'
)
exclude_mask = title_lower.str.contains(exclude_pattern, regex=True)

# --- brand-only matches that are fiction books published under "Dell" ---
book_indicator = r'\b(?:a novel|: a novel|a memoir)\b'
brand_only_book_mask = (brand_mask & ~keyword_mask) & title_lower.str.contains(book_indicator, regex=True)

# --- final filter ---
electronics_products = us_products[
    (keyword_mask | brand_mask_final) & ~exclude_mask & ~brand_only_book_mask
].copy()

print(len(electronics_products))

# --- accessory tagging (not filtered out, just flagged for the methodology write-up) ---
accessory_terms = r'\b(?:case|cover|sleeve|bag|backpack|decal|sticker|skin|mount|holder|screen protector|charger cable|cable)\b'
electronics_products['is_accessory'] = electronics_products['product_title'].str.lower().str.contains(accessory_terms, regex=True)
print(electronics_products['is_accessory'].value_counts())

60874
is_accessory
False    38717
True     22157
Name: count, dtype: int64

In [17]:
electronics_products.sample(100, random_state=7)[['product_title','product_brand']]

,product_title,product_brand
1706612,"Hdiwousp HDMI Adapter for Wii Converter, Wii to Hdmi Converter Output Video Audio Adapter with 1M HDMI Cable Wii2HDMI with 3.5mm Audio Output Supports 720/1080P All Wii Display Modes for Nintendo",Hdiwousp
721381,"Lenovo ThinkPad P52 15.6” FHD IPS Anti-Glare Mobile Workstation, i7-8750H, NVIDIA Quadro P1000, 8GB DDR4, 1TB HDD, Webcam, BT, Backlit Keyboard, Fingerprint Reader, Thunderbolt 3, Windows 10 Pro",Lenovo
1318452,Polaroid One-Step 600 Instant Camera,Polaroid
256401,Bose Soundsport Free Wireless Charging Case (Black),Bose
1272946,"Huawei B315s-22 Unlocked 4G LTE 150 Mbps Mobile Wi-Fi Router (3G/4G LTE in Europe, Asia, Middle East, Africa) (Black)",HUAWEI
253816,Vintage Silver RechicGu Western Big Horn Sheep RAM Goat Skull Leather Rodeo Bolo Bola Tie Necktie,RechicGu
863291,"Qinroiot Home Security Camera , Wireless Rechargeable Battery Powered Outdoor&Indoor Wi-Fi Camera with 1080P Night Vision,PIR Motion Detection, Two-Way Audio, IP65 Waterproof Support Cloud/SD Slot",Qinroiot
1621520,"Bluetooth Speaker Portable Retro Radio, Trenbader.com Vintage Bluetooth Speaker for iPhone Samsung. Retro Speaker for Home Office Outdoor, Wooden Vintage Style, Mic",Yogyro
441926,iPhone 11 Pro Leather Case Slim Thin iPhone 11 Pro Case Leather Anti-Scratch Protective Phone Cover Cases for Apple iPhone 11 Pro 5.8” 2019 (Brown),Jijaogara
475412,"Progo Ultra Absorbent Microfiber Cleaning Cloths for LCD/LED TV, Laptop Computer Screen, iPhone, iPad and More. (6 Pack)",Progo
484326,"Type C Charger, Dual Port Wall Charger, Car Charger, AndHot 2.1A Charging Block+USB Car Adapter+2-Pack 6ft Type C Fast Charging Cable for LG K51 Stylo 6 5 4 G9/G8/V60/V50/G7 ThinQ Q7+ V30 V20 G6 G5",ANDHOT
1301786,"MSI Aegis RS (Tower) Gaming Desktop, Intel Core i7-11700K, GeForce RTX 3080, 16GB Memory, 1TB SSD + 2TB HDD, WiFi 6, Liquid Cooling, USB Type-C, VR-Ready, Windows 10 Home Adv. (11TE-095US)",MSI
711765,"Bluetooth Land Line Phone Adapter - Bluetooth Version 3, 10 Meter Range, ISM Band Frequency (Bluetooth Headset is NOT Included)",WEIKAI LIMITED
1326313,Ultimate Ears Megablast Portable Wi-Fi/Bluetooth Speaker with Hands-Free Amazon Alexa Voice Control (Waterproof) with Charging Dock - Graphite Black (Renewed),Logitech
441192,"Apple iPad Mini 4 (32GB, Wi-Fi, Space Gray) (Renewed)",Apple
584258,"UBeesize Selfie Stick Tripod, Extendable and Portable Monopod with Wireless Remote Shutter, GoPro Adapter, Compatible with iPhone and Android Phone, Lightweight Camera, GoPro",UBeesize
1558765,"Cuddeback CuddeLink Cell Trail Camera (Verizon), Black Flash Medium Bundle (9 Items)",Cuddeback
704072,"SwissDigital Terabyte TSA-Friendly Water-Resistant Large Backpack, Business Laptop Backpack for Men with USB Charging Port/RFID Protection Big School Bookbag Fits up to 15.6"" Travel Laptop Backpack",Swissdigital
1614768,LG UHD 4K Region Free Blu Ray Disc DVD Player - PAL NTSC Ultra HD - USB - 100-240V 50/60Hz for World-Wide Use & 6 Feet Multi System 4K HDMI Cable,HDI
1638166,TOROSUS M.2 128GB NVME PCle 2280 Internal SSD High Performance Solid State Drive,TOROSUS
1707994,"Mpow M5 Pro Bluetooth Headset with Microphone, Wireless Headphones for Cell Phone, Noise Canceling Headset with Charging Base for PC, Laptop, Truck Driver, Office, Call Center, Skype",Mpow
251212,"Rexing FM Transmitter Car Charger w/Bluetooth 5.0, Wireless Audio Adapter Dual USB & Type C, Quick Charge 3.0, Enhanced Bass Music Player, Hands-Free Calling, Siri&Google Assistant Voice Control",REXING
889722,Large Vintage Canvas Messenger Shoulder Bag Crossbody Bookbag Business Bag for 15inch Laptop Brown,Dasein
1592505,"EBODA USB Headset with Microphone, Lightweight Comfort Wire PC Headphones with Inline Volume Control, Computer headsets for Skype/Zoom/Teams/Laptop/Call Center-Black",EBODA
1582758,"Fitpolo Smart Watches for Women Men, Smart Watch for Android Phones and iOS Phones, IP68 Swimming Waterproof Fitness Watch Pedometer Fitness Tracker Heart Rate Monitor, Full Touch Screen Smartwatch",Fitpolo
632158,"ROG Strix GA15DK Gaming Desktop PC, AMD Ryzen 7 5800X, GeForce RTX 3070, 16GB DDR4 RAM, 512GB SSD + 1TB HDD, Wi-Fi 5, Windows 10 Home, GA15DK-AS776",ASUS
618552,AC Portable Charger RAVPower 27000mAh AC Power Bank 85W (100W Max )AC Outlet Portable Laptop Charger Outdoors Travel Laptop External Battery Pack Compatible with HP Notebooks MacBook Nintendo Switch,RAVPower
1309418,OPPO Find X2 Lite (5G) CPH2005 Single-SIM 128GB + 8GB RAM (GSM Only | No CDMA) Factory Unlocked Smartphone - International Version (Moonlight Black),OPPO
1276142,"New Apple iPhone SE (128GB, (Product) RED) [Locked] + Carrier Subscription",Apple
347425,"Comply SmartCore Variety Pack Premium Memory Foam Earphone Tips, Fits Most Earphones, Noise Cancelling Soft Earbud Tips Conform to Your Ear for A Comfortable Secure Fit (Medium, 3 Pairs)",COMPLY
293926,"Dell 2-in-1 11.6-inch Touchscreen Chromebook Laptop, Intel Quad-Core Celeron N3450 Up to 2.2GHz Processor, 4GB DDR4 RAM, 32GB eMMC, WiFi, Bluetooth, Webcam, Chrome OS, 64GB Micro SD Card, Gray",Dell
1523571,POUT HANDS3 PRO Qi Fast Wireless Charging Charger Mouse Pad Mat for iPhone Xs Max/XR/X/XS/8/8 Plus Samsung Galaxy S10/S9/S8 Plus Note 9/8 (Dust Gray),POUT
642792,"Galaxy J3 2018 Case,Galaxy J3 Star Case,J3 Achieve Case,Galaxy Express/Amp Prime 3 Case,Galaxy J3 V 3rd Gen/J3 Orbit/J3 Aura/Sol 3 Case,Asmart Defender Cover Phone Case for Samsung Galaxy J3V,Green",Asmart
422816,"Reebok Women's Compression Running Shorts with Phone Pocket - High Waisted Performance Workout Short - 5 Inch Inseam - Quick Short Flint Grey Heather, X-Large",Reebok
1242778,"Dell P Series 21.5"" Screen LED-Lit Monitor Black (P2219H)",Dell
499783,OneGET MacBook Pro 13 Inch Case with Touch Bar Fashion Laptop Case MacBook Pro13 2016-2019 Release A1989 A1706 A1708 A2159 Glitter Bling PU Hard Shell Cover for Pro 13 (Glitter Silver),OneGET
1619156,"Macally Full-Size USB Wired Keyboard for Mac Mini/Pro, iMac Desktop Computer, MacBook Pro/Air Desktop w/ 16 Compatible Apple Shortcuts, Extended with Number Keypad, Rubber Domed Keycaps - Spill Proof",Macally
1349163,"Travel Cable Organizer Bag, Electronic Accessories Case Portable Double Layer Cable Storage Bag for Cord,Phone,Charger, Flash Drive, Phone, SD Card,Personal Items - (Grey)",Lanola
752682,"【Upgrade Version】 USB Charge Thread Charger Smart Over-Charge Protection, for USB Adapter Devices with LED Indicator Light Charge -【2-Pack】",Doreyi
677385,"LIFEMATE Scarf Camera Strap,DSLR Camera Strap Universal Neck Strap,Fabric of Bohemia Floral Scarf Camera Strap (Grey)",LIFEMATE
749658,[3 Pack] Kindle USB Cable A Male to Micro B 5FT iBarbe Sync and Quick Charging Cable Cord Durable Charging Cable for Use with All Kindle Tablets and e-Readers,iBarbe
866313,"Dell Touchscreen Chromebook 11 3120 Intel Celeron N2840, 4GB RAM, 16GB eMMC SSD Storage, Chrome OS, Black (Renewed)",Dell
679486,Sony Multi Zone Region Free Blu Ray Player - PAL/NTSC Playback - Zone A B C - Region 1 2 3 4 5 6,Sony
1658940,EBL Rechargeable AA Batteries 2800mAh 8 Pack and 8-Bay AA AAA Individual Rechargeable Battery Charger with 5V 2A USB Fast Charging Function,EBL
443880,Apple Silicone Case (for iPhone SE) - White,Apple
186035,"Seagate Expansion Portable Portable External Hard Drive USB 3.0 PC & PS4 (Renewed), Capacity:2.000GB (2TB)",Seagate
180968,"Wireless Charger, 3 in 1 Qi Standard Fast Wireless Charging Station Charger Stand Dock for iPhone 13/13 Pro/13 Pro Max/12/12 Pro/12 Pro Max/11/X/8,Apple Watch Series 7/6/SE/5/4/3/2,AirPods 2/Pro/3",SHARE SUNSHINE
579680,"Penen 10 inch Android Tablet PC, 5G Wi-Fi, 4GB RAM,64GB ROM, Octa -Core Processor, IPS HD Display, 3G Phablet with Dual Sim Card Slots, WiFi, Bluetooth, GPS, Tablets for Kids,M1 (Silver) (Black)",penen
349213,"Universal Remote Control with Scene Select and Find-It Feature Through Smartphone App Setup by Philips, Works with Samsung, Vizio, TCL, HiSense, Sony, Roku, Apple TV, Smart TVs, 6-Device, SRP2017B/27",Philips Accessories
283445,"Unique Tourbillon Phone Ring Holder Stand, 360° Rotation Cradle Cell Phone Metal Finger Ring Grip Universal Kickstand for All Apple iPhone Samsung Galaxy Huawei Smartphone (Gold)",Wooinhome
618989,"Razer Blade - Worlds Smallest 15.6in Gaming Laptop - 144Hz Full HD, 8th Gen Intel Core i7-8750H, GeForce GTX 1070 Max-Q, 16GB RAM, 512GB SSD (Renewed)",Razer
1203624,ASUS VA325H 31.5” Full HD 1080p 5ms IPS HDMI VGA Eye Care Monitor,ASUS
619139,"Razer Blade 15 Gaming Laptop 2019: Intel Core i7-9750H 6 Core, NVIDIA GeForce GTX 1660Ti, 15.6"" FHD 1080p 60Hz, 16GB RAM, 128GB SSD + 1TB, CNC Aluminum, Chroma RGB Lighting, Thunderbolt 3 (Renewed)",Razer
651804,Sennheiser Momentum On-Ear Headphone - Black,Sennheiser
207269,Crunch PX-1025.2 1000 Watts Power X Two Channel Car Audio Amplifier with Gravity Magnet Phone Holder Bundle,Crunch
187996,"Amazon Basics USB-C to Lightning Cable Cord, MFi Certified Charger for Apple iPhone 13/12/11, iPad, Black, 6-Ft",Amazon Basics
649668,"Scythe Mugen 5 CPU Air Cooler, 120mm Single Tower, Black Edition",SCYTHE
624135,Xiaomi Redmi 7A 16GB Dual SIM Unlocked GSM Phone w/ 13MP Camera - Matte Black,Xiaomi
618043,Raspberry Pi Zero v1.3 Development Board - Camera Ready,Raspberry Pi
1349164,"DDgro Electronics Travel Organizer, Waterproof Tech Accessories Pouch Bag for Keeping Certificates/Charger/Power Bank/Cables/Mouse/Earphone/students’ stationeries Organized (Small, Light Gray)",DDgro
621594,"BENTOBEN Case for iPhone 8, iPhone 7 Case, 3 in 1 Hybrid Case Shockproof Bumper Slim Hard Cover PC + Soft Silicone Rubber Interior Full Body Rugged Protective Phone Cover for iPhone 7/8, Red/Black",BENTOBEN
1666898,OIWAS Messenger Bag for Women - Canvas 15.6 Inch Laptop Satchel Computer Briefcase Mens Crossbody Bag School Backpack,OIWAS
860124,"weBoost Drive X - Vehicle Cell Phone Signal Booster | 5G & 4G LTE | Magnetic Roof Antenna | Boosts All U.S. Carriers - Verizon, AT&T, T-Mobile | Made in the U.S. | FCC Approved (model 475021)",weBoost
443947,"Tripod, Premium Phone Tripod,Portable and Flexible with Wireless Remote Shutter and Compatible for iPhone, Android, Digital Camera Sports GoPro(Black&White)",JSCT
704807,"LoveDeal 1/2 Inch Shank Slot Cutter Router Bit Set, 3 Teeth T Shape Molding Wood Milling Cutter, Adjustable 3 Wings Carbide Woodworking Tool - with 6 Pcs Slotting Cutter Blades, for Cabinet(6 Sizes)",LoveDeal
524749,IBERLS Surface 3 Tablet Charger Adapter for Microsoft 1623 1624 1645 Power Cord,IBERLS
442555,"Screen Replacement Compatible with iPhone 6S Plus Full Assembly - LCD 3D Touch Display Digitizer with Front Camera, Ear Speaker and Sensors, Fit Compatible with All iPhone 6S Plus White",SDYXJ
245718,"INTERGREAT Black L Shaped Computer Desk for Home Office, 56"" Large Glass L Desk with Storage Drawers, Corner Study Modern Table for Writing PC Laptop Gaming Workstation (Metal Steel)",INTERGREAT
587046,"JBL FLIP 5, Waterproof Portable Bluetooth Speaker, Pink (New Model)",JBL
528215,Ukwell Mini Classic Video Game Console Retro Gameboy with 2 NES Controllers Built-in 620 Classic Games Entertainment System TV Output Fun Gift,Ukwell
1210718,USB WiFi Adapter Wireless Network Adapters AC 600Mbps Dual Band 2.4G/5.8Ghz Wi-Fi Dongle with External Antenna for Laptop Desktop PC Compatible with Windows 10/8.1/8/7/XP/Vista /Mac OS X 10.6~10.15.3,EDUP
1683972,"Microsoft Surface Go (Intel Pentium Gold, 8GB RAM, 128GB) (MCZ-00001)",Microsoft
1331241,JBL TUNE 120TWS - True Wireless in-Ear Headphone - Blue,JBL
1598560,"Wiremold Cord Management Kit, In Wall Flat Screen TV Wire and Cable Hider Organizer, Recessed In Wall System, White, CMK70",Legrand - Wiremold
817342,"obVus Solutions Adjustable Laptop Tower Stand | Multiple Awards from Top Technology, Business and Health Magazines | Sitting to Standing in Seconds | Reduce Back and Neck Pain | Designed in The USA",obVus Solutions
1201597,Pyle 15.6-Inch 1080p LED TV | Ultra HD TV | LED Hi Res Widescreen Monitor with HDMI Cable RCA Input | LED TV Monitor | Audio Streaming | Mac PC | Stereo Speakers | HD TV Wall Mount (PTVLED15),Pyle
1359502,EBL Smart 8 Bay AA AAA Battery Charger for NiMH NiCD Rechargeable Batteries Build-in 2 USB Fast Charging Ports,EBL
865584,"Micro Center 32GB Class 10 Micro SDHC Flash Memory Card with Adapter for Mobile Device Storage Phone, Tablet, Drone & Full HD Video Recording - 80MB/s UHS-I, C10, U1 (5 Pack)",INLAND
492232,Logitech G933 Artemis Spectrum RGB 7.1 Surround Sound Gaming Headset (Renewed),Logitech
1276429,Eoneding Charging Port Replacement Kit USB Charging Charger Port Dock Connector Flex Cable Microphone Headphone Audio Jack Replacement Part for iPhone 6s 7 7plus 8 8 Plus x (Black for iPhone 7 Plus),Eoneding
1596629,"HP ENVY 5660 Wireless All-in-One Photo Printer with Mobile Printing, HP Instant Ink & Amazon Dash Replenishment ready (F8B04A) (Renewed)",HP
1701022,"VIZIO 65-Inch M6 Series Premium 4K UHD Quantum Color LED HDR Smart TV with Apple AirPlay and Chromecast Built-in, Dolby Vision, HDR10+, HDMI 2.1, Variable Refresh Rate, M65Q6-J09, 2021 Model",VIZIO
561095,Hard Travel Case for Anker Astro/RAVPower/Aukey/EasyAcc Classic/Ravpower Power Bank External Battery Pack Portable Charger Adaptor by CO2CREA,co2CREA
554488,"Noctua NH-U14S, Premium PC CPU AIR Cooler PC with NF-A15 140mm Fan for AMD Ryzen AM4 / Intel Socket LGA 1200, 1155, 1151 (Brown)",Noctua
1324209,"Charger Plug, 5Pack AndHot Dual Port USB Wall Charger Quick Charger Adapter 2.1A Fast Charging Block Brick Power Cubes for iPhone 12 11 SE XR X 8 7 6 Plus,iPad,Samsung S20 S10 S9 S8 S7,Android,Kindle",ANDHOT
401321,"4 Pack Safety Stainless Steel Tethers, DanziX Colorful Coated Lanyards for All GoPro Hero Series and Other Camera Devices,0.08 inch Diameter Cables,Protect Your Value - Red, Green, Silver, Black",DanziX
449457,"JBL ENDURANCE JUMP- Wireless heaphones, bluetooth sport earphones with microphone, Waterproof, up to 8 hours battery, charging case and quick charge, works with Android and Apple iOS (blue)",JBL
1235331,"Android Charger Cable, Costyle 3.1 Amp Dual 2 Port USB Wall Charger Home Travel Charging Block with 2 Pack 6 ft Nylon Braided Micro USB Cable Compatible for Samsung Galaxy S7 S6 Edge, HTC, LG (Blue)",Costyle
1619323,"2019 Apple MacBook Pro (16-inch, 16GB RAM, 512GB Storage, 2.6GHz Intel Core i7) - Space Gray",Apple
1553808,79STYLE 50pcs Spiral Coil Hair Ties No Crease Phone Cord Hair Ties Ponytail Holder Clear Hair Coil Scrunchies Colorful Hair Tie Spiral Coils in Bulk For Women Girls Thick Thin Hair (Crystal10 Colors -Large Size),79STYLE
462249,Tyler Portable Neon Pink Stereo CD Player with AM/FM Radio and Aux & Headphone Jack Line-in (TAU105-NPK),Tyler
1600553,"iBarbe Compatible for iPhone Xs Max 6.5"" Display Phone, Clear Anti-Scratch,Shock-Absorption Bumper Cover,Reinforced TPU Hybrid Cushion- Rosegold",iBarbe
215435,"Canon EF-M 11-22mm f/4-5.6 STM Lens, Black - 7568B002",Canon
1301461,"Ergonomic Mouse Pad with Wrist Support,Dooke Cute Wrist Pad with Non-Slip Rubber Base for Computer, Laptop, Home Office Gaming, Working, Easy Typing & Pain Relief Adorable Elephant",DOOKE
1715283,"Upgraded Version 3018 Pro CNC Router Kit, mcwdoit GRBL Control 3 Axis DIY CNC Engraving Machine, Wood Acrylic Plastic PCB MDF Milling Engraver with Offline Controller, CNC Router Bits, 300x180x45mm",mcwdoit
429647,HP LaserJet Enterprise P3015DN Printer (CE528A) - (Renewed),HP
1563310,Sharp Digital Clock with Alarm and Dual USB FastCharge Charging Ports - Charge Your Phone Bedside - Battery Back-up - Easy to Use,SHARP
822024,"Sony XR65A80J 65"" A80J 4K OLED Smart TV (2021) Bundle with Deco Gear Home Theatre Soundbar with Subwoofer, Wall Mount Accessory Kit, 6FT 4K HDMI 2.0 Cables and More",Sony
710947,tech21 Impact Clear Phone Case for Apple iPhone 7 - Smokey/Translucent,tech21
1600442,"elago Tablet Wall Mount Compatible with New iPad Mini, Compatible with iPad Pro, Compatible with iPad Air and Compatible with Most iPads, iPad Wall Mount (White) - Fits on Any Wall",elago

In [18]:
brand_only_matches = us_products[brand_mask & ~keyword_mask]
print(len(brand_only_matches))
brand_only_matches.sample(40, random_state=1)[['product_title','product_brand']]

6340

,product_title,product_brand
304558,"Corsair CRYSTAL 570X RGB Mid-Tower Case, 3 RGB Fans, Tempered Glass - White (CC-9011110-WW)",Corsair
492298,Logitech Multimedia Speaker System Z533 - Black,Logitech
230450,"Anker Alkaline AAA Batteries (24-Pack), Long-Lasting & Leak-Proof with PowerLock Technology, High Capacity Triple A Batteries with Adaptive Power and Superior Safety (Non-Rechargeable)",Anker
484393,LG K20 AT&T Unlocked 16 GB 4G LTE 5.3 inches 8 MP - Black (Renewed),LG
429463,"HP Envy 4520 Wireless All-in-One Photo Printer with Mobile Printing, Standard Ink Included, in Black (Renewed)",HP
1523607,Apple iPod Touch (32GB) - Product(Red) (Latest Model),Apple
766976,WD 4TB My Cloud Home Duo Personal Cloud Storage - WDBMUT0040JWT-NESN,Western Digital
1600180,"Apple iPad Air 2, 16GB, 4G + Wi-Fi - Gold (Renewed)",Apple
205418,Apple Silicone Case (for iPhone Xs Max) - White,Apple
821618,Sony SU-WL855 Ultra Slim Wall-Mount Bracket for Select Sony BRAVIA OLED and LED TVs,Sony
1600486,Apple Magic Keyboard (for 12.9-inch iPad Pro - 4th Generation) - US English,Apple
1614764,"2017 LG 4K Ultra HD 3D Blu-ray Player with Remote Control, HDR Compatibility, Upconvert DVDs, Ethernet, HDMI, USB Port, Black",LG
780207,Bose 161 Speaker System (Pair) - Black,Bose
1341544,Sony MHC-V21 High Power Audio System with BLUETOOTH,Sony
1600505,Apple iPhone 7 a1778 128GB GSM Unlocked (Renewed),Apple
210877,Apple iPod Touch (128GB) Space Gray,Apple
442569,"Apple iPhone 6S Plus, Fully Unlocked, 32GB (Renewed)",Apple
1373844,"LG 27 inch Ergo IPS UHD 4K Ultrafine Monitor, Black, 27BN88U-B",LG
1272804,"HP Sprocket 2x3"" Premium Zink Sticky Back Photo Paper (50 Sheets) Compatible with HP Sprocket Photo Printers.",HP
1582337,"ASUS TUF Gaming VG279QL1A 27” HDR Gaming Monitor, 1080P Full HD, 165Hz (Supports 144Hz), IPS, 1ms, FreeSync Premium, DisplayHDR 400, Extreme Low Motion Blur, Eye Care, HDMI DisplayPort",ASUS
643604,"SAMSUNG 65"" Customizable Bezel White Metal Finish (VG-SCFM65WM/ZA)",SAMSUNG
533217,"Acer T272HL bmjjz 27-Inch (1920 x 1080) Touch Screen Widescreen Monitor, Black",Acer
449437,JBL Stage A130 pr bookshelf speakers,JBL
608464,SONY PSP Playstation Portable Console JAPAN Model PSP-3000 Radiant Red (Japan Import),Sony
1331434,SAMSUNG (MB-ME64GA/AM) 64GB 100MB/s (U3) MicroSDXC EVO Select Memory Card with Full-Size Adapter,SAMSUNG
441194,"Apple iPad Mini 2 with Retina Display 16GB Wi-Fi + Cellular, Silver (Renewed)",Apple
1205703,"SAMSUNG UN65TU7000 65"" 4K Ultra HD Smart LED TV (2020) with Deco Gear Soundbar Bundle",SAMSUNG
776534,"Xiaomi Precision Screwdriver Set, 24 Magnetic Driver Bit Set, Pocket Screwdriver Tool Set, Mini Screwdriver Kit, Repair Tool Kit for Electronics…",Xiaomi
1339199,"TP-Link 24 Port Gigabit Switch | Smart Managed Switch w/ 4 SFP Slots | Rackmount | Limited Lifetime Protection | Support L2/L3/L4 QoS, IGMP and Link Aggregation | IPv6 and Static Routing (T1600G-28TS)",TP-Link
903072,"Anker European Travel Adapter, PowerExtend USB Plug International Power Adapter with 2 USB and 1 Outlet, US to Most of Europe EU Spain Iceland Italy France Germany",Anker
1698171,NETGEAR 4G LTE Broadband Modem - Use LTE as Primary Internet Connection (LB1120),NETGEAR
1348940,"LG 55UN7300PUF Alexa Built-In UHD 73 Series 55"" 4K Smart UHD TV (2020)",LG
547322,NETGEAR AC750 WiFi Range Extender with Gigabit Ethernet (EX6100),NETGEAR
1629412,"ASUS 27"" 1440P Eye Care Monitor (PB277Q) - QHD (2560 x 1440), 75Hz, 1ms, HDMI, DVI, VGA",ASUS
1317193,"2019 Newest Playstation 4 Holiday Bundle HESVAP Upgraded 2TB SSHD on Playstation PS4 Console Slim Bundle-Included 3X Games (The Last of Us,God of War,Horizon Zero Dawn) W/HESVAP Charging Station Dock",Sony
1596574,"HP 962XL High Yield Black and HP 962 Cyan, Magenta, Yellow Original Ink Cartridges Pack of 4 (3JB34AN)",HP
1729658,HP Wireless Elite Keyboard v2,HP
442447,"Apple iPhone 6s Plus, Boost Mobile, 128GB - Silver (Renewed)",Apple
410448,Dell Inspiron 5720 7720 Wireless DW1901 Half-Height Mini-PCI Express Card K2GW5,Dell
215433,Canon EF 20mm f/2.8 USM Wide-Angle Fixed Lens,Canon

In [19]:
def find_trigger(idx):
    text = title_lower.loc[idx] + ' ' + bullet_lower.loc[idx]
    m = re.search(pattern, text)
    return m.group(0) if m else None

sample = electronics_products.sample(100, random_state=99)
sample = sample.copy()
sample['matched_keyword'] = [find_trigger(i) for i in sample.index]
sample[['product_title', 'product_brand', 'matched_keyword']]

,product_title,product_brand,matched_keyword
1718989,HP 24mh FHD Monitor - Computer Monitor with 23.8-Inch IPS Display (1080p) - Built-In Speakers and VESA Mounting - Height/Tilt Adjustment for Ergonomic Viewing - HDMI and DisplayPort - (1D0J9AA#ABA),HP,NaN
499019,SinLoon 2 in 1 Combine Mini PCI-E M.2 NGFF & mSATA SSD to SATA 3.0 Adapter Converter (SATA3.0/M),SinLoon,ssd
1537098,BLU G9 PRO | 2020 | All Day Battery | Unlocked | 6.3” HD+ Infinity Display | 128 GB | Triple 48MP Camera | US Version | US Warranty | Nightfall,BLU,camera
1372500,for 2003-07 Honda Accord Radio Android 10.1 Double Din Car Stereo Bluetooth Support Backup Camera Mirror Link Play 2G RAM 32G ROM,EZoneTronics,camera
169577,"ZOEAST(TM) AirPods Case,Thick Soft Portable Keychain Finger Ring Protective Silicone Skin Cover Case [Front LED Not Visible] Compatible with Apple AirPods Earphone Charging Case 2&1 (Blue Stitch)",Earphone,earphone
584164,"Bike Phone Mount - Phone Holder for Bike, Phone Stand for Motorcycle, Silicone Phone Holder for Handlebar fits iPhone, Samsung, Huawei, GPS, Adjustable Rotation Phone Mount for Bike, Stroller",AMALEN,phone
1213536,HONONJO AV SWITCHER 4 Way Converter Video Audio Selector for TV with Remote Control Video Switch Box （Electrical Volts: 110V）,HONONJO,tv
208607,"30PCS Anime Sexy Girl Laptop Stickers for Adult, Waterproof Decals Stickers for Water Bottle Laptop Skateboard Motorcycle Car Bike Luggage Trolley Case Decoration(Sexy Girl Stickers)",Awolf,laptop
392063,"Gigabyte AERO 15 OLED XA-7US5130SP 15"" Thin Bezel Samsung UHD Amoled, i7-9750H, NVIDIA GeForce RTX 2070, Samsung 16GB RAM, 512GB Intel 760P SSD, W10 Pro, RGB KB, 94W Ultra Slim Laptop",GIGABYTE,ram
1333889,SENNHEISER SET840 -TV RF Stereo TV Assistive Listening Headphones System,Sennheiser,tv
649970,"sublue WhiteShark Mix Underwater Scooter Dual Motors, Action Camera Compatible, Water Sports Swimming Pool Scuba Diving for Kids & Adults",sublue,camera
316719,"MXCUSTOM Custom Apple iPhone 8 Plus iPhone 7 Plus Case, Customized Personalized with Photo Image Text Picture Design Make Your Own Phone Cases Covers [Clear Soft TPU Bumper+Hard PC Back] (CHT-CR-P1)",MXCUSTOM,phone
741217,"Black TV Stand for Flat Screen (RizerVue by SoCalVS) Tabletop (Up to 50"" Diagonal Screen)",SoCalVS,tv
817696,Appbot Riley Home Safety Movable Camera Robot,Appbot Riley,camera
684366,kikoo Cute Funny Spongebob Printing Candy Color Ultra Soft Phone Case for iPhone 11 Pro Max(for iPhone11 Yellow1),kikoo,phone
1306282,Charger for Nintendo Switch 5FT 15V 2.6A PD Fast Charging Supports TV Dock AC Power Supply Adapter Compatible with Nintendo Switch & Switch Lite Wall Charger with USB Type C Cable for Nintendo Switch,6amLifestyle,charger
439242,"Ablus 64 Pockets Mini Photo Album for Fujifilm Instax Mini 7s 8 8+ 9 25 26 50s 70 90 Instant Camera & Name Card (64 Pockets, Mint)",Ablus,camera
1222192,Casual Daypacks OMOUBOI Superbreak Backpack Laptop Backpack for Women & Men Fits Tourism School Business (Black),OMOUBOI,laptop
499716,Case Star MacBook Air 13 Inch Case Cover A1369 A1466 Laptop Plastic Hard Case Composition Notebook Series Pattern Laptop Hard Shell Case Cover (Old Version 2010-2017) -Black,Case Star,laptop
1601531,"(Renewed) Apple iPhone XS, US Version, 64GB, Space Gray - Unlocked",Apple,phone
1658304,Corsair K70 RGB MK.2 SE Mechanical RAPIDFIRE Gaming Keyboard - USB Passthrough & Media Controls - PBT Double-Shot Keycaps - Cherry MX Speed - RGB LED Backlit - White,Corsair,NaN
1401046,Translator Device Smart Voice Translator Use Alone Offline/Hotspot/WiFi Support 138 Languages High Intelligence Speed and Accuracy with 2.4 Inch Touch Screen Camera for Travelling Learning Business…,Fephant,camera
930151,"BANGE Weekender Carry-on Backpack,45L Expandable Travel Backpacks for Airplanes,Convertible Backpack Briefcase for Traveling,Water Resistant College 17.3” Laptop Backpack for Men & Women",BANGE,laptop
1711391,Infomir MAG322 IPTV Box No Built-in WiFi + HDMI Cable + Remote + Power Adapter + Battery,SDMarket,hdmi cable
1741635,"SAMSUNG 40-inch Class LED Smart FHD TV 1080P (UN40N5200AFXZA, 2019 Model)",SAMSUNG,tv
1599585,"Fujifilm Instax Mini 11 Lilac Purple Instant Camera with Twin Pack Instant Film, Ritz Gear Frame Stickers and Ritz Gear Hanging Frames",Fujifilm,camera
1331634,BMOUO Kids Case for Samsung Galaxy Tab E Lite 7.0 Inch - ShockProof Case Light Weight Kids Case Super Protection Cover Handle Stand Case for Children for Samsung Galaxy Tab E Lite 7 Inch Tablet - Rose,BMOUO,tablet
167963,"Anker Powerline III Flow, USB C to Lightning Cable for iPhone 13 13 Pro 12 11 X XS XR 8 Plus [MFi Certified, 3ft, Coral Pink] Supports Power Delivery, Silicone Cable (Charger Not Included)",Anker,charger
232841,Anime Stickers for Laptop 50pcs Water Bottle Luggage Snowboard Bicycle Skateboard Decal for Kids Teens Adult Waterproof Aesthetic Stickers,YOUTHSTORE,laptop
588127,"MOSISO Compatible with MacBook Pro 13 inch Case 2016-2020 Release A2338 M1 A2289 A2251 A2159 A1989 A1706 A1708, Plastic Hard Shell Case & Keyboard Cover Skin & Webcam Cover, Rose Quartz",MOSISO,webcam
818649,"SkyTech Blaze 3.0 Gaming PC Desktop – AMD Ryzen 5 3600 3.6GHz, RTX 3060 Ti 8G GDDR6, 1TB NVMe, 16G DDR4 3000, 600W Gold PSU, AC Wi-Fi, Windows 10 Home 64-bit, Black",SkyTech,ddr4
176937,"Ryobi P737D Portable Power Inflator with P118B Charger, 1.5 Ah Lithium-ion Battery and 15 Inch Buho Tool Bag",RYOBI,charger
1313947,"GL.iNet GL-AR750 (Creta) Travel AC VPN Router, 300Mbps(2.4G)+433Mbps(5G) Wi-Fi, 128MB RAM, MicroSD Storage Support, Repeater Bridge, OpenWrt/LEDE pre-Installed, Power Adapter and Cables Included",GL.iNet,router
1614299,Tools for Home Useful Kits Pro Lens Spanner Wrench 15-100mm Opening Tool for DSLR Camera Repair Open Helper,LC-Tools,camera
191326,"Sinwere Cute Retro Classic Cellular Phone Shaped Case for iPhone X iPhone Xs（5.8 Inch）, Soft Silicone 3D Cartoon Cover,Kids Girls Rubber Protector for iPhone X Xs (Pink)",Sinwere,phone
499685,"CCPK 13"" Laptop Sleeve 13 Inch Cover Protective Case Compatible with Apple MacBook Air 13.3 Inch Mac Pro M1 Surface Lenovo Dell HP Bag Computer Pouch Accessories Travel Carrying Case Neoprene, Black",CCPK,laptop
1260336,"Gaming Headset for Xbox One & PS4, AIMASON Noise Cancelling Over Ear Headphone w/Crystal Stereo Bass Surround Sound & Soft Memory Earmuffs, Headset for Games/Nintendo Switch/PC/Mac/Laptop",AIMASON,headphone
882126,"KEYWING Phone Camera Lens 3 in 1 Phone Lens Kit, 198 Fisheye Lens + 120 Super Wide-Angle Lens + 20x Macro Lens for iPhone Samsung Android Smartphone",KEYWING,phone
707859,Mushkin Pilot-E – 1TB PCIe NVMe – Opal Data Encryption – M.2 (2280) Internal Solid State Drive (SSD) – Gen3 x4 – 3D TLC - (MKNSSDPE1TB-D8),Mushkin,ssd
1262966,FITZOOM Kids Waterproof Smart Watch GPS/LBS Tracker for 3-12 Years Boys Girls Smart Watch Phone with SOS Two Way Call Micro Chat Camera Anti-Lost Math Game Touch Screen Games Christmas Birthday Gifts,FITZOOM,phone
851259,10W Computer Speakers for Desktop PC Powerful Speakers USB Powered Monitor Speakers for Desktop Computer/PC/TV/Laptop Gaming Speaker,Smalody,desktop computer
372273,"Sqodok Floral Backpack for Women Teen Girls, Waterproof School Bookbag with Lunch Bag&Pencil Case, Canvas Laptop Bag 15"" Cute Travel Daypack Lightweight Student Rucksack for School",Sqodok,laptop
642571,"mCover iPearl Hard Shell Case for 12.3"" Samsung Chromebook Plus XE513C24 Series (NOT Compatible with Older XE303C12 / XE500C12 / XE503C12 Models) Laptop - Chromebook Plus XE513C24 (Red)",mCover,chromebook
383580,"Walker Edison Tall Wood Universal TV Stand with Open Storage For TV's up to 58"" Flat Screen Living Room Storage Entertainment Center, 52 Inch, Grey",Walker Edison,tv
1333371,"ZUMIMALL Wireless Outdoor WiFi Security Camera, Rechargeable Battery Powered, PIR Motion Detection Cameras for Home Security, Two Way Audio, Night Vision, Waterproof, Cloud/SD, 2PCS",ZUMIMALL,security camera
1523063,Winegard RVW-395 Sensar IV White DTV/HD TV Antenna,Winegard,tv
372276,School Backpack Set Girls Kids Laptop Bookbag Lunch Bag 3 Pieces Floral Daypack Pencil Bag 3 in 1 (D Flower Black),Antjoint,laptop
650734,"SideTrak Slide Portable Monitor for Laptop 12.5"" FHD 1080P IPS Attachable Laptop Screen | Efficient USB Power | Compatible with Mac & Chrome 13"" -17"" Laptops (Patent Pending) | Black",SideTrak,laptop
552234,Nikon D750 24.3MP HD 1080p FX-Format Digital SLR Camera (Body)(Renewed),Nikon,camera
583851,"LeYi Compatible with LG Tribute Empire Case, LG Aristo 3/2/2 Plus/Rebel 4 LTE/Phoenix 4/Tribute Dynasty/Zone 4 Phone Cases with [2PCS] Tempered Glass Screen Protector, Ring Kickstand Cover, Red",LeYi,phone
1530365,"iMah BT18433/BT28433 2.4V 750mAh Ni-MH Battery Also Compatible with AT&T VTech Cordless Phone CS6229 BT184342 BT284342 BT183348 BT283348 BT8300 BT1011 BT1018 BT1022 BT1031 2SN-AAA55H-S-J1, 2-Pack",iMah,phone
1618375,"Arlington TVBU505-1 Recessed TV Box Wall Plate Kit Paintable 2-Gang, White",ARLINGTON,tv
416944,"HDMI Splitter, Hagibis HDMI Switch Box, 4K@60Hz Bi-Directional HDMI Switcher 1 in 2 Out or 2 in 1 Out, No External Power Required, Supports 4K 3D HD 1080P for Xbox PS4 Laptop Projector PC HDTV",HAGIBISTECH,laptop
401357,"Motorcycle Helmet Chin Mount Strap Compatible with GoPro Hero 10 Black,Hero 9/8/7/6/5 Black, AKASO/Campark/DJI Action Camera, with Short Connection",SKEZN,camera
643701,"for Samsung S10+, Galaxy S10 Plus, Art Design Soft Back Case Phone Cover, HOT12771 Girly Flower Golden Retriever Dog 12771",True Love Jewellery Pty Ltd,phone
782251,"CARMEL CONCEPT Professional Padfolio with Bonus Business Card Holder, Compatible with iPad Pro 9.7""/Mini, Macbook Pro 13"" or tablet devices. Vegan Leather Portfolio Folder with Zippered Closure",CARMEL CONCEPT,tablet
443560,"Headphone Adapter for iPhone 7/7Plus 8/8Plus for iPhone X/XS/XR/11 Pro max Audio Jack to 3.5mm Earphone Adaptor 【Audio +Charge】 Cable, iPhone Dongle Extension Cord Cable AUX Female Support All iOS",Gan,headphone
741098,"Samsung QN65Q60AA 65 Inch QLED 4K Smart TV (2021) Bundle with Deco Gear Home Theater Soundbar with Subwoofer, Wall Mount Accessory Kit, 6FT 4K HDMI 2.0 Cables and More",SAMSUNG,processor
1619285,"Apple MacBook Pro 15in Laptop Intel QuadCore i7 2.3GHz (MD103LL/A),16GB Memory, 480GB Solid State Drive, ThunderBolt (Renewed)",Apple,laptop
499729,"Mac Book Air Charger, AC 45W Magnetic Power Adapter Charger for Mac Book Air (After Mid 2012)",koea,charger
1642507,"Unigear Paddleboard Deck Bag, Mesh Storage Bag Sup Accessories with 4pcs D-Ring Patches with Waterproof Phone Case",Unigear,phone
211097,2 Pack Remote Case Compatible with Apple TV 4K/5th and HD 4th Generation - Auswaur Shock Proof Silicone Remote Cover Case Compatible with Apple TV HD 4 and 4K/5th Gen Siri Remote Controller -Black Red,Auswaur,tv
851266,"Jitterbug Smart2 No-Contract Easy-to-use Smartphone for Seniors by GreatCall,Black",GreatCall,smartphone
332170,"RRJQW Phone Ring Holder Stand,Stitch Phone Ring Stand Holder 360 Rotation Finger Ring Grip Stand for Cellphones,Smartphones and Tablets",RRJQW,phone
403664,LilGadgets Connect+ PRO Kids Premium Volume Limiting Wired Headphone w/SharePort and Microphone – Best Childrens Headphones for School – Head Set Ear Phones for Children – Green,LilGadgets,headphone
552316,"Nikon 16384 X1000 Matte Illuminated x-MRAD Reticle Spotting Scopes, 6-24x50SF, Black",Nikon,NaN
586516,MyClipKneeboard - Simplest Tablet Kneeboard - Universal,TietCo,tablet
286493,Charger Power Cord Fit for Bose Soundlink Mini 1st Gen Only 12V Power Supply AC Adapter Fit for Bose SoundDock XT Speaker P/N 626209-1300 371071-0011 Replacement,VIFOCUFY,charger
521011,Messenger Bag Multifunctional Pocket Travel Work College Handbag Fits 14 Inch Laptop Ipad Water Bottle Shoulder Bag Navy,YUOTO,laptop
1220152,"Accmor Stroller Cup Holder with Phone Holder/Organizer, Universal Bike Cup Holder, 2-in-1 Bottle Holder for Stroller, Bike, Wheelchair, Walker, Scooter,Black",Accmor,phone
1675564,"321OU Smart Watch Compatible iOS Android iPhone Samsung for Men Women, Make/Answer Calls, Checking Messages Support, Bluetooth Fitness Tracker Watch with Pedometer Camera SIM SD Card Slot (White)",321OU,camera
1597863,"iOttie Easy One Touch 4 Dash & Windshield Universal Car Mount Phone Holder Desk Stand for iPhone, Samsung, Moto, Huawei, Nokia, LG, Smartphones, Black",iOttie,phone
429393,"OMEN 25L Gaming Desktop PC, NVIDIA GeForce GTX 1660 Super, 10th Generation Intel Core i5-10400F Processor, HyperX 8 GB RAM, 512 GB SSD, Windows 10 Home (GT12-0020, 2020)",OMEN,processor
179110,"PERLESMITH Full Motion TV Wall Mount Bracket for Most 13-30 inch TVs and Monitors, Flat and Curved TVs up to 33lbs, Wall Mount TV Bracket, Tilt Swivel and 14-inch Extension, Max VESA 100x100mm, PSXSF2",PERLESMITH,tv
204536,"Boxiki Travel Money Belt - RFID Blocking Money Belt and Safe Waist Bag, Secure Fanny Pack for Men and Women, Fits Passport, Wallet, Phone and Personal Items. Running Belt, Waist Pack",Boxiki Travel,phone
210842,"[Apple MFi Certified] Lightning to 3.5mm Headphone Jack Adapter, iPhone Headphone Adapter, Aux Jack Headphone Adapter Compatible for iPhone 11 XS XR X 7 7P 8 8P",burkemany,headphone
474316,Broonel Grey Invisible Lightweight Laptop Computer Stand - Compatible with The Samsung Series 7 Chronos Notebook 1TB HDD NP780Z5E,Broonel,laptop
899099,Educator Dual Lead Charger for Series 800 and 1200 Training Collars with Round Charging Ports,Educator,charger
1367208,Wisenet SDH-C94087BF 8 Channel 4K DVR Video Security System 2TB Hard Drive and 8 4K Weather Resistant Bullet Cameras (SDC-99447BF),Wisenet,hard drive
1312161,PARALLAX POWER Components 55RU 55 Amp Converter/Charger,Parallax Power,charger
319342,"Groovy Daisy Flowers Decal Sticker For Use On Laptop, Helmet, Car, Truck, Motorcycle, Windows, Bumper, Wall, and Decor Size- [6 inch] / [15 cm] Wide / Color- Gloss White",N&N Stickers,laptop
642529,"Wasabi Power Battery (2-Pack) and Charger for Samsung BP85A, EA-BP85A and Samsung PL210, SH100, ST200F, WB210",Wasabi Power,charger
346425,"LUDOS Clamor Wired Earbuds in-Ear Headphones, Earphones with Microphone and Volume Control, Noise Isolating Memory Foam Eartips with Replacements, Tangle-Free Cord for iPhone, iPad, Computer, Laptop",LUDOS,laptop
429481,"HP Probook 650 G5 15.6"" Notebook - 1920 X 1080 - Core i7 i7-8565U - 16 GB RAM - 16 GB Optane Memory - 256 GB SSD - Windows 10 Pro 64-bit - Intel UHD Graphics 620 - in-Plane Switching (IPS) Techno",HP,ram
319353,USA American Flag Sunflower Sticker Cup Laptop Cooler Flower car Vehicle Window Bumper Wall Vinyl Decal Graphic,215 Decals,laptop
608701,"【2K, Smart Motion Tracking】 Hiseeu Snowman 3MP Wireless Security Camera for Home, WiFi Pet Camera for Baby, Nanny, Dog and Cat, 360-degree, 2 Way Audio, Night Vision, Supported TF Card Cloud Record",Hiseeu,security camera
1213033,"Vasttron Mini Projector,Portable Movie Projector,Small Multimedia Home Theater Video Projector,Compatible with Full HD 1080P HDMI,VGA,USB,AV,TV Box,DVD,Laptop,Smartphone,PS4",VASTTRON,laptop
433854,"CUK GS66 Stealth by_MSI 15 Inch Gaming Notebook (Intel Core i9, 64GB RAM, 2TB NVMe SSD, NVIDIA GeForce RTX 3080 16GB, 15.6"" FHD 300Hz 3ms, Windows 10 Pro) Professional Gamer Laptop Computer",Computer Upgrade King,ram
840521,"Mediasonic HFR2-SU3S2 PRORAID 4 Bay 3.5"" SATA Hard Drive Enclosure - USB 3.0 & eSATA",Mediasonic,hard drive
701464,simpletome Adhesive Power Strip Holder Wall Mount Organizer for WiFi Router Surge Protector Remote Controller (8 Pack),simpletome,router
172163,"2020 Samsung Galaxy Tab A7 10.4’’ (2000x1200) TFT Display Wi-Fi Tablet Bundle, Qualcomm Snapdragon 662, 3GB RAM, Bluetooth, Dolby Atmos Audio, Android 10 OS w/Tigology Accessories (32GB, Gray)",Samsung Electronics,tablet
191029,Maxboost Galaxy S9 Plus Case HyperPro Series with Heavy Duty GXD-Gel Protection [Black/Clear] Enhanced Hand-Grip TPU Cushion + Transparent Hybrid S9+ Cover for Samsung Galaxy S 9 Plus Phone (2018),Maxboost,phone
711873,"TELETIES - Spiral Hair Coils - Ponytail Holder Hair Ties for Women - Phone Cord Hair Ties - Strong Grip, No Rip, Water Resistant, No Crease Hair Tie Coils - 3 pack (Small, Coral)",Teleties,phone
826976,"O’Bright Dimmable LED Desk Lamp with USB Charging Port (5V/2A), Full Range Dimming LED, Table Lamp with USB Charger, Flexible Gooseneck, Office Desk Lamp/Bedside Lamp, Vintage Design (Aluminum)",O'Bright,charger
741422,M8 Screws for Samsung TV M8x45mm TV Mounting Bolts Screws with ABS Spacers,TV Bolts,tv
554074,LHMUYU No Soliciting Seriously Don't Ring The Bell Don't Make It Weird Smile You're On Camera Home Decoration Garden Yard Flags Sign for Indoor and Outdoor Polyester Flag Double Sided 12 x 18 Inch,NaN,camera
272695,YHC Vented Bicycle Helmet Strap Mount Adapter for Xiaomi Xiaoyi Action Sport Camera,YHC,camera
1603211,SUPAREE (Plug and Play) Spare Tire Brake Light Wheel 3rd Third Brake Light JL Spare Tire Light for Wrangler JL JLU 2018-2021 with Back Up Camera,SUPAREE,camera
176037,"DEFEWAY 16ch CCTV Camera Security System with 16Channel 1080N DVR, 16 Weatherproof 720P HD Cameras, Indoor & Outdoor, 100ft Night Vision, Motion Detection, 2TB Hard Drive",WD DEFEWAY,camera
443198,Vonna Phone Case Replacement for iPhone 12 Pro Mini 5G 11 Xs Max Xr 8 X 7 Plus 6s 5s SE Cover Silicone Fruit Cute Adorable Girly Flexible Print Women Summer Design Fruit Smooth Soft Watermelon a058,Vonna,phone

In [20]:
# did the publisher-Dell problem survive the title-only fix?
us_products[(us_products['product_brand'].str.lower() == 'dell') & 
            (brand_mask & ~keyword_mask)][['product_title','product_brand']].head(20)

,product_title,product_brand
170855,"Dell 1.92TB 12Gb/s 2.5"" SAS Solid State Drive Bundle with Tray, Compatible with Dell PowerEdge R640, R740, R740XD, R440, R540, R840, R940, T440, T640 Servers",Dell
174709,"Dell Inspiron 14 5400 2 in 1 - 14 Inch FHD Touchscreen, Intel Core i5, 12GB Memory, 256GB Solid State Drive, Windows 10 Home (Latest Model)- Titan Grey",Dell
179376,"Dell P2421D 24 Inch 1440p QHD, IPS Thin Bezel Monitor, HDMI, DisplayPort, VESA Certified, Black",Dell
179381,"Dell Curved Gaming Monitor 27 Inch Curved Monitor with 165Hz Refresh Rate, QHD (2560 x 1440) Display, Black - S2722DGM",Dell
179997,"Dell Dual Monitor Stand – MDS19, Black",Dell
185518,Dell U4919DW UltraSharp 49-inch QHD 5120x1440 32:9 Curved Monitor Bundle with Tech Smart USA Elite Suite 18 Standard Editing Software Bundle and 1 Year Extended Warranty,Dell
188967,"HGST 6TB SATA III 3.5-inch HDD | HUS726060ALE614 | Enterprise Internal Hard Disk Drive Bundle with Compatily Screwdriver | Compatible with Desktop Computers, Workstation PC, Mac, NAS & CCTV DVR",Dell
195062,Dell BIZLINK DisplayPort to DVI Dual Link Adapter USB Powered - XT625 / CN-0XT625,Dell
203110,"Alienware 25 Gaming Monitor - AW2518Hf, Full HD @ Native 240 Hz, 16:9, 1ms Response Time, DP, HDMI 2.0a, USB 3.0, AMD FreeSync, Tilt, Swivel, Height-Adjustable (Renewed)",Dell
203111,Alienware 25 Gaming Monitor - AW2518H (Renewed),Dell
203464,"Dell Inspiron AIO 3475, i3475-A407BLK-PUS, 7th Gen AMD A9-9425, 23.8-Inch FHD (1920 X 1080), 8GB, 1TB SATA HD",Dell
254444,True Crime: The Novel,Dell
254758,The Horse Whisperer: A Novel,Dell
279607,"Dell 21 Printer Series Ink Cartridge for Dell All-In-One printers P513w P713w V313 V313w V515w V715w, 2-Pack, (Black and Color)",Dell
279608,Dell Y498D Series 21 Standard Capacity Black Cartridge for V313w V515w P513w V715w P713w Ink,Dell
279609,Dell 21 Color Ink Cartridge (XG8R3/330-5274/Y499D),Dell
279612,Dell Y499D 21 Standard Capacity Color Ink Cartridge for V313w/V515w/P513w/V715w/P713w,Dell
279613,Genuine OEM brand name Dell Series 21 V313/V715 Clr Ink 3305274 (170 Yield) Y499D,Dell
302156,Dell S5840CDN Color Laser Smart Printer,Dell
304707,Dell SE2216H 22 -Inch Screen LED-Lit Monitor,Dell

In [21]:
conglomerates = ['samsung', 'lg', 'sony', 'panasonic']
conglomerate_brand_only = us_products[
    brand_lower.isin(conglomerates) & brand_mask & ~keyword_mask
]
print(len(conglomerate_brand_only))
conglomerate_brand_only.sample(min(40, len(conglomerate_brand_only)), random_state=3)[['product_title','product_brand']]

1933

,product_title,product_brand
349206,Sony Universal Remote Control,Sony
1677699,Sony ICF-P36 Portable AM/FM Radio - Black,Sony
855715,SONY X800 2K/4K UHD - 2D/3D - Wi-Fi 2.4/5.0 Ghz - Clear Audio - Multi System All Region Blu Ray Disc DVD Player 100-240V 50/60Hz Auto,Sony
484681,LG Tone Ultra HBS-835 Bluetooth Stereo Headset - Wireless with JBL Signature Sound (Black),LG
1718624,"LG NanoCell 80 Series 65” Alexa Built-in 4k Smart TV (3840 x 2160), 60Hz Refresh Rate, AI-Powered 4K Ultra HD, Dolby Cinema, Dolby Vision (65NANO80UPA, 2021)",LG
1301610,Spider-Man: Homecoming [Blu-ray],Sony
484475,LG LP1017WSR 115V Portable Air Conditioner with Remote Control in White for Rooms up to 250-Sq. Ft. (Renewed),LG
606736,"Panasonic Water Jet Nozzle Replacement, Compatible with EW-DJ10-W, EW-DJ10-A Dental Flossers, White, 2 Count",Panasonic
809688,"LG WM3488HW 24"" Washer/Dryer Combo with 2.3 cu. ft. Capacity, Stainless Steel Drum in White",LG
679745,Sony NW-ZX300 Hi-Res Walkman 64GB Digital Music Player (Black),Sony
744632,"LG 34UM68-P UltraWide Monitor 34” 21:9 IPS Display, sRGB Over 99%, On-Screen Control with Screen Split, FreeSync,Height & Tilt Adjustable Stand",LG
249271,Bloody Roar,Sony
1614779,"LG Nano 8 Series 75SM8670PUA TV, 75"" 4K UHD Smart LED NanoCell, 2019 model",LG
1298052,Panasonic 2.2 Cu. Ft. 1250W Genius Sensor Countertop Microwave Oven with Inverter Technology in Black,Panasonic
1677695,Sony ICF-F10 Two 2 Band FM/AM Portable Battery Transistor Radio,Sony
1716866,LG EBR41531303 Genuine OEM Main Control Board for LG Refrigerators,LG
1250944,"LG LW1216HR 11,500/12,000 230V Window-Mounted Air Conditioner with 9,200/11,200 BTU Supplemental Heat Function, 12000, White",LG
174726,Panasonic Lumix 14mm f/25 G Aspherical Lens for Micro Four Thirds Interchangeable Lens Cameras (White Box),Panasonic
1582326,"LG 27GN750-B UltraGear Gaming Monitor 27” FHD (1920x1080) IPS Display, 1ms Response, 240HZ Refresh Rate, G-SYNC Compatibility, 3-Side Virtually Borderless Design, Tilt, Height, Pivot Stand - Black",LG
1537326,Sony DSXA415BT Digital Media Receiver with Bluetooth & Satellite Radio,Sony
484542,LG SK5Y 2.1 Channel 360W High Resolution Audio Sound Bar (2018 Model),LG
805673,"LG SIGNATURE OLED88Z9PUA Alexa Built-in Z9 88"" 8K Ultra HD Smart OLED TV (2019)",LG
1699380,Samsung DVD-V5650 DVD/VCR Combo,SAMSUNG
388768,"Samsung Microwave Glass Cooking Tray - 11.25""",SAMSUNG
1675524,"LG 70UM7370PUA Alexa Built-in 70"" 4K Ultra HD Smart LED TV (2019)",LG
673444,"Samsung 70"" 4K Smart LED TV, 2018 Model",SAMSUNG
1357948,"LG 34GL750-B 34 Inch 21: 9 Ultragear Curved Wfhd (2560 X 1080) IPS 144Hz G-SYNC Compatible Gaming Monitor,Black",LG
497847,"PANASONIC LUMIX ZS200 15X Leica DC Lens with Stabilization, 20.1 Megapixel, Large 1 inch Low Light Sensor (DC-ZS200S USA Silver)",Panasonic
1597443,"SAMSUNG Sound+ SWA-W700 Wireless Subwoofer, Front Firing Design with 10-Inch Driver, Ultra-Deep 27Hz Bass, Pairs Automatically with Sound+ Soundbars",SAMSUNG
1248460,Sony RDR-GXD455 Single Deck DVD Recorder with Built In HD Tuner,Sony
1331683,Samsung DC97-07448D Washing Machine Shipping Bolt,SAMSUNG
1342065,[Pack of 2] Panasonic CR2354 3V Lithium Cell Blister Packaging Battery,Panasonic
643632,Samsung Xpress M3015DW Laser Printer,SAMSUNG
1690779,Samsung Galaxy S8 64GB G950U T-Mobile GSM Unlocked - Orchid Gray (Renewed),SAMSUNG
484549,Sony SHAKEX10 High Power Home Audio System with Bluetooth,Sony
484200,LG Black Stainless Steel Series 1.5 cu. ft. NeoChef™ Countertop Microwave with Smart Inverter and EasyClean,LG
484431,"LG 65NANO99UPA Alexa Built-In NanoCell 99 Series 65"" 8K Smart UHD NanoCell TV (2021)",LG
249521,Panasonic DMP-BD45 Ultrafast-Booting Blu-ray Disc Player (Black),Panasonic
1675504,Samsung Electronics F-IRM-US-2 SmartThings Motion Sensor,SAMSUNG
185635,LG Xpression C410 Qwerty Keyboard Slider Cellphone GSM Unlocked - Blue,LG

In [22]:
sony_brand_only = us_products[(brand_lower == 'sony') & brand_mask & ~keyword_mask]
print(len(sony_brand_only))
sony_brand_only.sample(min(40, len(sony_brand_only)), random_state=4)[['product_title','product_brand']]

705

,product_title,product_brand
426975,Horizon Zero Dawn: Complete Edition - PlayStation 4 Digital Download Code,Sony
755213,Sony 12T120VR 120-Minute Premium VHS Cassettes (12-Pack) (Discontinued by Manufacturer),Sony
1515915,Sony UBP-X800M2 4K Ultra HD Blu-ray Player with HDR with 2-6ft. High Speed Premium HDMI Cables and 14ft Ethernet Cable Bundle,Sony
1717646,Sony SEL35F14Z Distagon T FE 35mm f/1.4 ZA Standard-Prime Lens for Mirrorless Cameras,Sony
679588,Sony HAPZ1ES 1TB Hi-Res Music Player System,Sony
819615,Sony SELP1650 16-50mm Power Zoom Lens,Sony
542297,Sony STR-DN1080 7.2-Channel Home Theater AV Receiver Bundled with Active Subwoofer and Seven Sony Speakers (9 Items),Sony
825604,Days Gone PS4 Playstation 4,Sony
654812,The ICO and Shadow of the Colossus Collection (Renewed),Sony
679769,"Sony XBR85X950H 85"" X950H 4K Ultra HD LED TV (2020) with Deco Gear Soundbar Bundle",Sony
1557622,Crash Bandicoot: Collector's Edition (Crash Bandicoot: Warped / CTR: Crash Team Racing / Crash Bash),Sony
452235,"Back up Plan, the / Sex Tape - Vol / Bad Teacher (2011) / Playing for Keeps - Vol / Bounty Hunter, the (2010) / Ugly Truth, the - Vol - Set",Sony
909787,The Celestine Prophecy,Sony
1393533,Sony CDP-CE500 5-Disc CD Changer (Black),Sony
679750,Sony NW-A55 16GB Walkman Hi-Res Portable Digital Music Player with 16 GB Card and Case Bundle (3 Items),Sony
1341550,Sony XB01 Bluetooth Compact Portable Speaker Black (SRSXB01/B) (Renewed),Sony
679738,"Sony E series SDXC UHS-II Card 128GB, V60, CL10, U3, Max R270MB/S, W120MB/S (SF-E128/T1), SFE128/T1,Black,Small",Sony
336862,Sony HT-G700 3.1ch Soundbar with Dolby Atmos/DTS:X Cinematic Surround Sound & Bluetooth Wireless Technology Home Theater Bundle w/Extended 1yr Coverage + Deco Gear 2X HDMI Cables + Streaming Kit,Sony
464008,Sony MDR-XB200/P (MDRXB200-Pink) XB Extra Bass Series On-Ear Headphones,Sony
679666,SONY Waterproof and dustproof Walkman with Bluetooth Wireless Technology NW-WS623 (Blue),Sony
758068,Sony PlayStation Vita WiFi [PlayStation Vita],Sony
1698341,PlayStation 4 Slim 1TB Console - Black (Renewed),Sony
1717918,"Sony 32-inch 720p Smart LED TV (KDL32W600D, 2016 Model)",Sony
679759,"Sony WH-CH510 Wireless On-Ear Headphones, Black (WHCH510/B) with Knox Gear Hard-Shell Case Bundle (2 Items)",Sony
1716385,"Sony SELP18105G E PZ 18-105mm F4 G OSS , Black",Sony
679644,Sony NP-FW50 Lithium-Ion 1020mAh Rechargeable Battery,Sony
1696919,Sony ICFCDK50 Under Cabinet Kitchen CD Clock Radio,Sony
1677706,Sony SEL24240 FE 24-240mm f/3.5-6.3 OSS Zoom Lens for Mirrorless Cameras (Renewed),Sony
679486,Sony Multi Zone Region Free Blu Ray Player - PAL/NTSC Playback - Zone A B C - Region 1 2 3 4 5 6,Sony
810166,Sony KD43X80J BRAVIA 43-Inch 4K Ultra HD HDR LED Smart TV (2021 Model Year) Home Theater Headphones Bundle (2 Items),Sony
608269,The Show 19 Playstation 4,Sony
817045,Sony XBR-75X940E 75-inch 4K HDR Ultra HD Smart LED TV (2017 Model),Sony
673413,"Sony KD65X85J 65-inch X85J 4K Ultra HD LED Smart TV (2021 Model) Bundle with Deco Gear Home Theater Soundbar with Subwoofer, Wall Mount Accessory Kit, 6FT 4K HDMI 2.0 Cables and More",Sony
1343963,Star Wars: Episode III: Revenge of the Sith (PS2 Classic) - PS3 [Digital Code],Sony
1677667,Sony STRZA5000ES 9.2-Channel AV Receiver,Sony
679754,SONY WH-1000XM3 Wireless Noise canceling Stereo Headset(International Version/Seller Warrant) (Black),Sony
625766,Jerry Maguire,Sony
755190,Sony SLV-N71 4-Head Hi-Fi VCR,Sony
600883,New Sony Playstation Portable PSP 3000 Series Handheld Gaming Console System (Renewed) (Mystic Silver),Sony
365945,PlayStation 4 Final Fantasy Type-0 [Japan Import],Sony

In [23]:
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

validation_sample = electronics_products.sample(200, random_state=100)[['product_title', 'product_brand', 'is_accessory']]
validation_sample.to_csv('electronics_filter_validation_sample.csv', index=False)
validation_sample

,product_title,product_brand,is_accessory
1243179,"Anyshock Desk Mat, Extended Gaming Mouse Pad Large 31.5"" x 15.7"" XL Keyboard pad with Stitched Edges Non Slip Base, Water-Resistant Computer Laptop Desk Pad for Office and Home(White Marble)",Anyshock,False
1600447,"Matone Tablet Holder with Strongest Large Suction Cup, Universal Tablet Stand Phone Holder for iPhone iPad Series/Samsung Galaxy Tabs/Fire HD and More, Great for Mirrors/Windows/Walls",Matone,True
443564,Headphone Adapter,Jafuam,False
172689,"CZ Portable 5V/5.1A 4-USB Port Smart Quick Charge Travel Charger with Holder Function for Smartphones & Tablets & Power Bank & Bluetooth Headset, 100-240V Wide Voltage, US Plug (Color : Black)",Nologo,True
217653,AOO Keyboard Cleaner Gel Dust Cleaning Mud Laptop Keyboards PC Tablet Screen Interior Car Detailing Kit (5-Pack(14.10oz/400g)),AOO,False
442436,"Apple iPhone 6S, 64GB, Space Gray - For AT&T / T-Mobile (Renewed)",Apple,False
464967,"8.0 inch Tablet Case, Mptie Universal Protective PU Leather Case Cover for All 7.5-8.5 inch iPad Mini 1 2 3 4 5,Galaxy Tab A 8.0/Tab E 8.0, F ire HD 8 and More (Books)",Motie,True
1597850,TIKRO iPhone Charger [Apple MFi Certified] 5 Pack - 6FT Lightning Cable Nylon Woven High Speed Data Sync Cord Compatible iPhone 12 11 Pro Max X 8 7 6S Plus SE - Color,TIKRO,True
179978,"ASUS VE278H 27"" Full HD 1920x1080 2ms HDMI VGA Back-lit LED Monitor",ASUS,False
1212956,Asus VG248QG 24” G-Sync Compatible Gaming Monitor 165Hz Full HD 1080P 0.5ms DP HDMI DVI Eye Care (Renewed),ASUS,False
1619339,"Apple 16"" MacBook Pro (2019) Intel Core i9 2.3GHz, 16GB RAM, 1TB SSD, macOS, Silver (Renewed)",Apple,False
1578251,"IMDEN Bluetooth 5.0 FM Transmitter for Car, 3.0 Wireless Bluetooth FM Radio Adapter Music Player FM Transmitter/Car Kit with Hands-Free Calling and 2 USB Ports Charger Support USB Drive",IMDEN,False
524146,"Professional Ultra SanDisk 64GB MicroSDXC Card for Samsung Galaxy Note 8.0 Smartphone is custom formatted for high speed, lossless recording! Includes Standard SD Adapter. (UHS-1 Class 10 Certified 30MB/sec)",SanDisk,False
233028,"Studio3 Replacement Headband,Studio 3.0 Head Band Repair Fix Parts Compatible with Studio3 & Studio 2.0 Wired/Wireless B0500 B0501 Headphone (Shadow Gray)",QKIIP,False
256044,"Dual-Lens Endoscope,DEPSTECH Wireless Borescope, HD Inspection Camera with 6 Adjustable LED, Zoom Waterproof Snake Camera for Android & iOS Smartphone Tablet-16.4Ft",DEPSTECH,False
322404,"Pioneer DDJ-SX3 DJ Controller for Serato DJ Pro Bundle with Gearlux Laptop Stand, Headphones, and Austin Bazaar Polishing Cloth",PIONEER,False
1698187,"SNANSHI Printer USB Cable 10 Ft,USB Printer Cable USB 2.0 Type A Male to Type B Male Printer Scanner Cable for HP, Canon, Lexmark, Epson, Dell, Xerox, Samsung etc",SNANSHI,True
1217293,LiPo Charger Lipo Battery Balance Charger RC Charger RC Car Battery Charger Discharger 150W 10A 1-6S AC/DC for Li-ion/Life/NiCd/NiMH/LiHV/PB/Smart Battery(Battery Charger Adapter),Haisito,False
1333270,Fantom Drives Xbox One 2TB High Performance Seagate Firecuda Gaming SSHD (SSD+Hard Drive) and Storage Hub - Xbox-2TB-SSHD,Fantom Drives,False
423948,HOTA D6 Pro Smart Charger AC200W DC650W 15A Lipo LiIon NiMH Battery Wireless Charging for RC FPV Drone,HOTA,False
216029,"ASUS ROG Rapture WiFi Gaming Router (GT-AC5300) - Tri Band Gigabit Wireless Router, Quad-Core CPU, WTFast Game Accelerator, 8 GB Ports, AiMesh Compatible, Included Lifetime Internet Security",ASUS,False
1706512,"Wireless Keyboard Mouse, Jelly Comb 2.4GHz Ultra Slim Full Size Rechargeable Wireless Keyboard and Mouse Combo for Windows, Laptop, Notebook, PC, Desktop, Computer (White and Silver)",Jelly Comb,False
202704,"Echo Show 8 (2nd Gen, 2021 release) | HD smart display with Alexa and 13 MP camera | Glacier White",Amazon,False
673473,"Smart Watch,Smartwatch for Android Phones, Smart Watches Touchscreen with Camera Bluetooth Watch Phone with SIM Card Slot Watch Cell Phone Compatible Android Samsung iOS Phone XS X 8 10 11 Men Women",AnnBushes,False
679530,SONY ICF-C211-BLK AM/FM Clock Radio (Discontinued by Manufacturer),Sony,False
429103,"HP 250 G7 15.6"" LCD Notebook - Intel Core i5 (8th Gen) i5-8265U Quad-core (4 Core) 1.60 GHz - 4 GB DDR4 SDRAM - 500 GB HDD - Windows 10 Pro 64-bit (English) - 1366 x 768 - Intel UHD Graphics 620",HP,False
1544156,S-ZONE Canvas SLR DSLR Camera Shoulder Messenger Bag with Bottom Tripod Compatible with Cannon,S-ZONE,True
556438,Adaptive Fast Charger kit with USB Type C Cable (4ft) Compatible with Samsung Galaxy S8/S8 Plus/S9/S10/S10 Plus/S10e/ S20/S20 Plus/S21/S21 Ultra/Note 8/Note 9/Note 10/Note 20 Ultra (Black),VectorTech,True
1698334,"Samsung Galaxy A10 32GB A105M 6.2"" HD+ Infinity-V 4G LTE Factory Unlocked GSM Smartphone - Black",Samsung Electronics,False
672756,"Sony SRS-XB13 Extra BASS Wireless Portable Compact Speaker IP67 Waterproof Bluetooth, Black (SRSXB13/B)",Sony,False
1345303,D-uang Eleven of Stranger Starry Sky Backpack Girls Boys School Backpack Lightweight Dream of Exploring Things Bookbag Laptop Travel Shoulder Daypack,D-uang,True
844349,"Bluetooth Speakers, DOSS SoundBox Plus Portable Wireless Bluetooth Speaker with 16W HD Sound and Deep Bass, Wireless Stereo Pairing, 20H Playtime, Wireless Speaker for Home, Outdoor, Travel -Black",DOSS,False
210889,"Apple Mac Mini MD387LL/A Desktop - 2.5GHz Intel Core i5, 4gb Memory, 500gb Hard Drive (Renewed)",Apple,False
295938,Funko Pop! DC Heroes Batman 1966 TV Series - Riddler Chase Variant Vinyl Figure (Bundled with Pop Box Protector CASE),Funko,True
1276589,3.5mm Headphones/Earbuds Jack Adapter Aux Cable Earphones/Headphone Converter Accessories Compatible with Phone,KOROMU,True
1675356,"Pruveeo C2 1080P Dual Dash Cam 2.7 inch LCD with Infrared Night Vision,G-Sensor, Dual Front and Inside, 170° Wide Angle, G-Sensor, Loop Recording ,24H Parking Monitor for Cars Truck Taxi Drivers",PRUVEEO,False
216206,AT&T Cell Phone Signal Booster T-Mobile US Cellular Band12/17 4G LTE Cell Signal Booster ATT Cell Phone Booster Repeater Amplifier 700Mhz FDD Mobile Signal Booster with Ceiling+Yagi Antennas for Home,PHONELEX,False
1716574,"Cyclace Exercise Bike Stationary 330 Lbs Weight Capacity- Indoor Cycling Bike with Comfortable Seat Cushion, Tablet Holder and LCD Monitor",Cyclace,True
1557284,"CAIYUNL for LG Stylo 5 Case,Luxury Bling Glitter Sparkle Studded Rhinestone Shockproof Hybrid Dual Layer Hard Phone Case Heavy Duty Rugged Protective Cover Women Men for LG Stylo 5-Black Purple Flower",CAIYUNL,True
808360,"Canon PowerShot Vlogging Camera [G7X Mark III] 4K Video Streaming Camera, Vertical 4K Video Support with Wi-Fi, NFC and 3.0-inch Touch Tilt LCD, Silver",Canon,False
644098,"Samsung Galaxy A70 128GB, GSM Unlocked Smartphone - Blue",Samsung Electronics,False
256346,"Bose Soundbar 500, Black Bass Module 500 for Soundbar 500/700",Bose,False
441850,Apple Silicone Case (for iPhone 11 Pro) - Midnight Blue,Apple,True
205777,"Dragon Touch Y88X Pro 7"" Kids Tablet, 2GB RAM 16GB Android 9.0 Tablets, Kidoz Pre-Installed with All-New Disney Content WiFi Only",Dragon Touch,False
1212097,"ARCTIC Freezer 50 TR (INCL. A-RGB Controller) - Dual Tower CPU Cooler for AMD Ryzen Threadripper with A-RGB, Two Pressure-Optimised Fans, with 8 Heatpipes for Maximum Performance",ARCTIC,False
630592,"Cat 8 Ethernet Cable 5 ft Shielded, 26AWG Lastest 40Gbps 2000Mhz SFTP Patch Cord, Heavy Duty High Speed Cat8 LAN Network RJ45 Cable- in Wall, Outdoor, Weatherproof Rated for Router, Modem, Gaming",Dacrown,True
256272,"Smof Premium 30 Pin Bluetooth Adapter for Sounddock,Replace iPod/Phone Link Bose/JBL/Car, Bluetooth Audio Receiver 3.5 mm AUX Output-Female",Smof,False
614193,"Wireless Car Charger Mount,Qi-Certified Car Wireless Charging Stand Compatible with iPhone 11 pro/X/XS Max/XR/8/Samsung Galaxy S9 / S10/,Silicone Car Phone Holder Dashboard Desk",ELE-Jiaruila,True
667413,"Bedocia Peach Roses Print Floral Lanyard Women&Girls Cute Lanyard for Keys,Id Badge Holder,Card,Cell Phone,Wallet",Bedocia,True
1596605,"MOSISO Laptop Sleeve Compatible with MacBook Pro 16 inch 2021 M1 Pro/M1 Max A2485/2019-2020 A2141/Pro Retina 15 A1398, 15-15.6 inch Notebook, Polyester Multifunctional Briefcase Bag, Burgundy",MOSISO,True
1511841,"Sony Compact Stereo Sound System for House with Bluetooth Wireless Streaming NFC, Micro Hi-Fi 50W, CD/DVD Player with Separate Speakers, FM Radio, Mega Boost, USB Playback and Charge, Remote Control",Sony,False
1646020,Red and Black Wave Phone Grip,Unknown,False
1668515,"Blink XT2 Outdoor/Indoor Smart Security Camera with cloud storage included, 2-way audio, 2-year battery life – Add-on camera for existing Blink customers",Blink Home Security,False
230794,"Schumacher FR01235 Battery Charger with Engine Starter, Boost, and Maintainer - 100 Amp/30 Amp, 6V/12V - for Tractors, Cars, and Trucks",Schumacher,False
204731,"Anmino GPS Smart Watch (GPS +Barometer+Altimeter+Compass),Full HD Touchscreen,All-Day Heart Rate and Activity Fitness Tracker,Pedometer,Calorie Counter,Sleep Tracker,Bluetooth smartwatch",anmino,False
642792,"Galaxy J3 2018 Case,Galaxy J3 Star Case,J3 Achieve Case,Galaxy Express/Amp Prime 3 Case,Galaxy J3 V 3rd Gen/J3 Orbit/J3 Aura/Sol 3 Case,Asmart Defender Cover Phone Case for Samsung Galaxy J3V,Green",Asmart,True
557682,"Learning Tablet Toy, Baby Tablet Preschool Child Early Educational Touch Pad for Fun Learn Number ABCs Spelling Animal Pink-3",LIFTREN,False
1525395,Asus RT-AC1200G IEEE 802.11ac Ethernet Wireless Router,ASUS,False
1278154,2 Final Fantasy Sephiroth Squall Leonhart Mascot Cell Phone Charm Strap Set,Final Fantasy,False
1601108,"Mengfly Flower Phone Ring Holder, Canvas Electronics Organizer Bag Sets, Waterproof, Anti-Theft, Sturdy, for Phone, iPhone, Power Bank, Office, Travel, Outdoor; Stand Grip and Handbag Included （5pcs）",Mengfly,True
635687,"ASUS Modem Router Combo - All-in-One DOCSIS 3.0 32x8 Cable Modem + Dual-Band Wireless AC2600 WIFI Gigabit Router – Certified by Comcast Xfinity, Spectrum, Time Warner Cable, Charter, and Cox",ASUS,True
1572579,"External Hard Drive, Slim Portable Hard Drive Storage Drive Type C USB 3.0 Compatible with PC, Laptop and Mac (2TB, Black)",Lanist,False
780489,"Tosima Wireless TV Speakers for Hearing Impaired, Senior Hearing Assistance Speaker for TV, Soundbox for Hard of Hearing and Elderly (TV Need 3.5mm Jack or Audio Out Plug) Black",Tosima,False
1576317,120-180 Degree Portable and Detachable 3 in1 Clip On Fish Eye Wide Angle Macro Lens for Smartphone for Smartphone and Tablet,Henanxi,False
1367202,Wisenet SDH-C84085BF 8 Channel Super HD DVR Video Security System with 2TB Hard Drive and 8 5MP Weather Resistant Bullet Cameras (SDC-89445BF) (Renewed),SAMSUNG,False
1601673,"Dailylux Case for iPod Touch 7, iPod Touch 6, iPod Touch 5, Cute Phone Case Glitter Pearly-Lustre Slim Shell Protective Soft TPU Back Cover for Girls Women, Leopard White",Dailylux,True
1378606,TACTACAM Reveal X Cellular Camera | VERIZON,TACTACAM,False
686994,"Crucial BX500 120GB 3D NAND SATA 2.5-Inch Internal SSD, up to 540MB/s - CT120BX500SSD1",Crucial,False
1572760,Nike Air Force 1 AF1 26L Laptop Shoulder Tote Bag Teal BA4989,Nike,True
1357948,"LG 34GL750-B 34 Inch 21: 9 Ultragear Curved Wfhd (2560 X 1080) IPS 144Hz G-SYNC Compatible Gaming Monitor,Black",LG,False
1654892,"Ceiling Light Battery Operated, Starxing 5 inch Puck Light with Remote Control, Shower Light with DC Charger/ Sticker for Kitchen Cabinet Closet Bedroom Stairs (Multicolor,RGB)",Starxing,True
1531523,"Cooper Desk PRO [XL Adjustable Folding Laptop Desk] - Height & Tilt Angle | Leather Top for Work, Study, Bed | Reading Stand, Drawer (Midnight Black)",Cooper Cases,False
1213006,"ASUS VivoBook 14 Thin and Light Laptop, 14” FHD IPS Display, Ryzen 5 3500U, 8GB DDR4 RAM, 256GB PCIe SSD, Webcam, Backlit Keyboard, Fingerprint Reader, WiFi Bluetooth, Windows 10 Home",ASUS,False
678337,Mighty Max Battery 100 Watts 100W Solar Panel 12V - 18V Poly Off Grid Battery Charger for RV Brand Product,Mighty Max Battery,False
283383,"FYY Designed for iPhone XR Case, Luxury PU Leather Wallet Phone Case with Card Holder Flip Folio Protective Shockproof Cover [Kickstand Feature][Wrist Strap] for iPhone XR 6.1"" 2018 Red",FYY,True
735808,"ALNbes Health and Fitness Smartwatch with Heart Rate Monitor, Smart Watch for Home Fitness Tracking, Yoga, Exercise Bike, Treadmill Running, Compatible with iPhone and Android Phones for Women Men",ALNbes,False
767574,"Webcam Light Stand for Live Stream, Selfie Ring Light with Webcam Mount for Logitech C925e, C922x, C930e,C922,C930,C920,C615,Brio 4K",AceTaken,True
808125,Canon EOS 5D Mark IV DSLR Full Frame Camera with EF 50mm F1.8 STM Lens + EF 75-300mm F4-5.6 III Lens Kit Prime Travel Bundle,Canon Intl.,False
1556233,"Greenworks 40V 12-Inch Cordless Chainsaw, 2.0Ah Battery and Charger Included 20262",Greenworks,False
562625,Outdoor TV Antenna - 1byone 720°Omni-Directional Reception TV Antenna Built-in Amplifier Enhance UHF for Home/RV/Attic/Marine Up to 150 Miles with 32ft Coax Cable Free HDTV Channels,1 BY ONE,True
690223,UPBRIGHT AC Adapter Compatible with Chicago Electric Model 38391 12 Volt Jump Starter 12V DC Power Systems 3 in 1 Jump Start Air Compressor 08884 Harbor Freight Tools Power Supply Battery Charger PSU,UPBRIGHT,False
843595,Access All Areas: The Diversity Manifesto for TV and Beyond,Faber & Faber,False
754444,"QIBOX Charger Compatible with Fitbit Versa Lite/Versa (Not for Versa 2), 4.2ft USB Replacement Charging Cradle Cable Stand for Versa Lite Smart Watch",QIBOX,True
866737,"2021 Newest HP 15 15.6"" FHD Laptop Computer, Intel Quad-Core i5-1135G7 up to 4.2GHz (Beat i7-1065G7), 8GB DDR4 RAM, 512GB PCIe SSD, AC WiFi, Bluetooth 5.0, Webcam, Type-C, Windows 10, 64GB Flash Drive",HP,False
1593885,"ECHOGEAR TV Cable Hider for Wall Mounted TV - 48"" Long Cord Raceway Can Be Cut to Any Length - Cable Cover Installs On The Wall in Minutes with A Screwdriver to Hide Wires",ECHOGEAR,True
1692338,"Screen Cleaner Kit - Best for LED & LCD TV, Computer Monitor, Laptop, and iPad Screens – Contains Over 1,572 Sprays in Each Large 16 Ounce Bottle – Includes Premium Microfiber Cloth",Screen Mom,False
900005,"Personal AM/FM Pocket Radio Portable VR-robot, Mini Digital Tuning Walkman Radio, with Rechargeable Battery, Earphone, Lock Screen for Walk/Jogging/Gym/Camping",VR-robot,False
482464,"IdeaPad Charger 65W 45W Round Tip Power Supply AC Adapter for Lenovo IdeaPad 330-14, 330-15, 330-17, 510-15, 330s-14, 330s-15 Lenovo Flex 6-14 Laptop Charger",Ostrich,False
476253,"HP 58A | CF258A | Toner-Cartridge | Black | Works with HP LaserJet Pro M404 series, M428 series",HP,False
1657141,"Radenso XP Radar Detector with False Alert Filtering, GPS Lockouts, USA Technical Support, Red Light and Speed Camera Alerts",Radenso,False
1378603,Bushnell Trail Camera CORE S-4K No-Glow_119949C,Bushnell,False
893688,RAM Golf Ultimate Hard-Sided Travel Cover,RAM,True
796415,"LETSCOM Smart Watch with Heart Rate Monitor, Compatible with iPhone Samsung Android Phones, IP68 Waterproof Activity Tracker Smartwatch with Calorie Counter Sleep Monitor for Women Men",LETSCOM,False
741431,"Suptek Aluminium Alloy Lockable RV TV Wall Mount for 13-24 inch LED, LCD, OLED and Flat Screen TVs on Motor Home Camper Truck Trailer, 10.04 inch from The Wall Swivel/Tilt/Extension Arm (MA2790-1)",suptek,True
1716778,"DJI FPV Combo - First-Person View Drone UAV Quadcopter with 4K Camera, S Flight Mode, Super-Wide 150° FOV, HD Low-Latency Transmission, Emergency Brake and Hover, Gray",DJI,False
758709,New XUMO XRT122 TV Remote Control for Vizio D39H-D0 D50U-D1 D55U-D1 D58U-D3 D65U-D2 E32-C1 E32H-C1 E40-C2 E40X-C2 E43-C2 E48-C2 E50-C1 E55-C1 E55-C2 E60-C3 E65-C3 E65X-C2 E70-C3,VIZIO,False
1567149,"Artisul D16 15.6 Inch Drawing Tablet with Screen FHD Graphics Drawing Monitor Pen Display with 8192 Levels Pen Pressure 7 Customized Shortcut Keys and a Dial for Drawing,Design and Home Office",Artisul,False
1288207,"Aduro LED Bluetooth Speaker with Pulsating Lights, Wireless Color Changing Portable Outdoor Party Tower Speaker Universal",Aduro,False
387867,Garmin Venu GPS Smartwatch with AMOLED Display and Wearable4U Ultimate Black Earbuds with Charging Power Bank Case Bundle,Wearable4U,True
704802,"Yakamoz 1/4 Inch Shank 3-Wing Adjustable Slot Cutter Router Bit Set with Bearings | 6-Picecs Slotting Cutting Blades, 1/2 Inch Cutting Depth, 6 Different Cutting Widths",YAKAMOZ,False
1751878,Man and His Symbols,Dell,False
1648068,"Pixel 4 XL case Clear with Screen Protector with 9H Tempered Glass, Soft TPU Bumper Protective case Designed for Google Pixel 4 XL case with Cushioned Corners, Anti-Drop Thin Silicone Best Phone case",Beautifirm,True
462573,"Kids Camera, 21MP HD 3M Waterproof Digital Camera for Kids, 2.0 Inch LCD Display, 8X Digital Zoom,Flash and Mic for Boys Girls Kids（Blue）",KIDSCAM,False
475736,"50PCS Sexy Lady Women Laptop Stickers for Adult,Waterproof Decals Stickers for Water Bottle Laptop Skateboard Motorcycle Car Bike Luggage Trolley Case Decoration",CRODER,True
716878,The Lady Vanish 16x9 Widescreen Television,NaN,False
913153,Body Camera Built-in 32GB Memory Card 1080P Police Video Recorder Wearable Portable Security Cam Webcam with Night Vision Pocket Clip IR Dash Cam for Home/Outdoor/Law Enforcement/Cop Guard,KSADBOSSBO,False
695425,"Streamlight 90503 Survivor LED Flashlight with Charger, 6-3/4-Inch, Orange - 175 Lumens",Streamlight,False
1511008,"elevavie 1TB USB Flash Drive, Thumb Drive,Portable USB Memory Stick,1000GB Pen Drive Come with Keychain for PC/Laptop/External Storage Data(1000GB Silver)",elevavie UURM K,False
818342,EACHSHOT Insta360 One X2 Panoramic Action/Sport Camera 5.7K Video 10M Waterproof FlowState Stabilization 1630mAh Battery Insta 360 OneX2,EACHSHOT,False
774776,"JSB 39.37"" Small Folding Computer Desk with Storage Bag and Hook, Writing Desk Modern Industrial Work Table Laptop Desk for Home Office (White)",JSB,True
710236,Artinova Elephant Wooden Pen Cup Pencil Holder for Desk Decor Desk Organizer with Cell Phone Stand ARTA-0057,Artinova,True
433785,Intel NUC 10 Performance Kit – Intel Core i3 Processor (Tall Chassis),Intel,False
346425,"LUDOS Clamor Wired Earbuds in-Ear Headphones, Earphones with Microphone and Volume Control, Noise Isolating Memory Foam Eartips with Replacements, Tangle-Free Cord for iPhone, iPad, Computer, Laptop",LUDOS,False
415444,"Home Bluetooth Speaker, ASIMOM 30W Powered Speakers, Wireless Stereo Pairing, 10H Playtime, Loud Bass, Modern Wireless Bluetooth Speaker for Home, Office and Gift",ASIMOM,False
639929,eSamcore Samsung Galaxy S8 Plus Case – Luxury Marble Ring Holder Phone Cases + Vent Car Phone Mount for Samsung Galaxy S8 Plus 6.2 Inch [Emerald Green],eSamcore,True
767598,"2020 NexiGo 1080P HD Webcam with Built-in Microphone, Widescreen USB HD Web Camera for Zoom Meeting YouTube Skype FaceTime Hangouts, PC/Mac/Laptop/Desktop, Video Calling Recording Conferencing",NexiGo,False
422287,"Webcamera_usb USB Camera Module Full HD 1080P Webcam Module,2MP Web Camera Module with Cmos OV2710 Image Sensor,High Fps 480p@100fps Web Cam Module,Webcamera Module for Windows,Linux,Mac,Raspberry Pi",webcamera_usb,False
188609,Apevia CF6015S-5 (5 Pk) 60mm x 60mm x 15mm Black Case Fan W/4PIN Molex + 3PIN Motherboard Adapter,APEVIA,True
417100,"VCE 2-Pack HDMI Mini Adapter Gold Plated Mini HDMI to Standard HDMI Connector 4K Compatible for Camera, Camcorder, DSLR, Tablet, Video Card",VCE,False
885216,4TB Transcend StoreJet 25H3 2.5-inch USB3.0 Portable Hard Drive,Transcend,False
176357,"Monocular Telescope, 16X52 High Power Monocular with Smartphone Holder & Tripod, Night Vision Monocular for Adults Kids - BAK4 Prism Dual Focus for Bird Watching, Camping, Travelling",crownly,True
185824,"NexiGo N950 4K Zoomable Webcam with 5X Digital Zoom, Sony Senor and Dual Stereo Microphone, Low Light Correction for Zoom Skype MS Teams, Laptop MAC PC Desktop",NexiGo,False

In [6]:
electronics_ids = set(electronics_products['product_id'])
electronics_examples = shopping_queries_dataset_examples[
    (shopping_queries_dataset_examples['product_locale'] == 'us') &
    (shopping_queries_dataset_examples['product_id'].isin(electronics_ids))
]
print(electronics_examples['query'].nunique(), "distinct electronics queries")
print(len(electronics_examples), "electronics query-product judgment rows")
print(electronics_examples['esci_label'].value_counts())

NameError: name 'electronics_products' is not defined

In [25]:
electronics_examples['query_length'] = electronics_examples['query'].str.split().str.len()
unique_queries = electronics_examples.drop_duplicates(subset='query')[['query', 'query_length']]
print(unique_queries['query_length'].describe())

count    17998.000000
mean         3.612401
std          1.958622
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         29.000000
Name: query_length, dtype: float64

In [31]:
unique_queries = electronics_examples.drop_duplicates(subset='query')[['query', 'query_length']]

print("=== 1-2 words ===")
print(unique_queries[unique_queries['query_length'] <= 2].sample(100, random_state=1)['query'].to_list())

print("\n=== 3-4 words ===")
print(unique_queries[unique_queries['query_length'].between(3, 4)].sample(100, random_state=1)['query'].to_list())

print("\n=== 5-6 words ===")
print(unique_queries[unique_queries['query_length'].between(5, 6)].sample(100, random_state=1)['query'].to_list())

print("\n=== 7+ words ===")
print(unique_queries[unique_queries['query_length'] >= 7].sample(100, random_state=1)['query'].to_list())

=== 1-2 words ===
['small rig', 'mmcx cable', 'desktop pc', 'motorcycle', 'lg ud58', 'fgteev book', 'ips curved', 'cr123a 3v', 'canon t7i', 'pink wristlet', 'princess toys', 'earbud', 'gadget guard', 'inazuma gw250', 'plan b', 'assassins creed', 'motorola', 'usb hdmi', 'kindle', 'baywatch pop', 'rolling backpack', 'colageno capsules', 'baofeng radio', 'sonos subwoofer', 'snow shovel', 'blu', 'dji ronin', 'ps4 fan', 'printing calculators', 'digital frame', 'aelfox', 'pbt98 pyle', 'side boards/buffet', 'victsing', 'e katerina', 'giftcards', 'black pods', 'motorolaone', 'mi phone', 'fibroplex 240', 'bape', 'wood engravers', 'labradoodle decal', 'bts', 'bushnell wingman', 'stephanie bower', 'spectre', 'logitech', 'hidden storage', 'ota tuner', 'gsm', 'summicron-m 35mm', 'stacked chests', 'xiaomi watch', 'cd/dvd printers', 'billie eilish', 'bride hanger', 'horns', 'makeup eraser', 'hide wire', 'sports bag', 'snaptain', 'samsung buds', 'nintendo+switch+games+dead cells', 'magic mount', 'popcocket', 'motorola apx', 'truck stickers', 'sport headphones', 'lightbox shelf', 'photography backgdrop', 'hubsan zino', 'low voltage', 'computer mouse', 'phone magnet', 'pdf software', 'fenjun', 'desktop ram', 'alcohol pads', 'vr oculus', 'girls watch', 'coffin purse', 'monitor stand', 'saitek yoke', 'wooden desk', 'rinnegan contacts', 'kenwood', 'ear wax', 'roku player', 'senheiser urbanaite', 'gadgets', '32gk650f-b', 'small laptop', 'nakamichi shockwafe', 'turntables', 'pet camera', 'jaybird', 'lg27gn950-b', 'prokector', 'tactical pouches']

=== 3-4 words ===
['toilet paper hol', 'best friend phone case', '40v worx battery', 'wifi door sensor', 'zip id case camo', 'newest ipad model', 'iphone 7 plus cases', 'passport wallet with zipper', 'leopard handbags for women', 'iphone 6 plus case', 'coax to hdmi adapter', 'usb disk drive', 'airpods pro hook', 'moon nebula light', 'plantronics wireless headset', 'night projector for baby', 'iphone 10xs max case', 'lightning charging cable angled', 'iphone tmobile unlocked', '4k 2mp action camera', 'car ac smell', 'garage door opener', 'fairy tail backpack', 'airsoft gun pack', 'vape without nicotine', 'solaray chromium picolinate 500mcg', 'cpu cooler am4', 'self propelled mowers', 'iphone 7 case lv', 'music tote bag', 'usb lunch box', 'learning english for kids', 'old rca tv', 'backpack england style', 'epyc amd cpu', 'custom pop socket', 'cable cord 25 feet', 'iphone 7 charging port', '7.5 hp vfd', 'xbox one x bundle', 'xbox preorder x', 'jeep car accessories', 'usb mic podcast', 'mini snack dispenser', 'mini circle purse', 'otterbox iphone 11 pro', 'spy camera outdoor', 'iphone cord charger', 'bang and olufsen earbuds', 'large stickers for adults', 'iphone 7 case silicone', 'the 6th friend dvd', 'ifit for nordictrack treadmill', 'emergency solar crank radio', 'modem router combo xfinity', 'jbl charge 4', 'airpod case gucci', 'king l magic massager', 'womens leather backpack', 'heat guns electric', 'corner tv stand', 'ring doorbell 2', 'panther airpod case', 'spacers & standoffs', 'tiny cars for boys', 'vanith mirror with lights', 'acoustimass surround system', 'rj45 female union', 'cute japanese clothing', 'msi 27 inch monitor', 'ssd m.2 nvme 500gb', 'turtle galaxy s9 case', 'on off road motorcycles', 'synology 6 bay', '270 degree hdmi adapter', 'hyundai i10 defense', 'iphone jc programmer', 'cellairis iphone x case', 'double adhesive tissue holder', '1tb ssd samsung', 'long thin light', 'garmin fenix 3 hr', 'handheld game console', 'battery operated fan', '30 pin cable', 'nebo slim plus', 'gaming pc cyberpowerpc', 'cheap 3d wallpaper', 'gaming mix amp', 'cheap spy camera', '5v white led', 'canon r5 adapter', '2x4 8gb ddr4', 'display s8 plus samsung', 'samsung a 50 phone', 'vtech action cam 180', 'hex arena pro', 'mobil bluetooth printer', 'iphone xr hybrid cases', 'emergency flashlights for vehicles']

=== 5-6 words ===
['school supplies for high school', 'puma rs shoes for men', 'stylus pens for touch screens', 'pull down tv mount over fireplace', 'levoit desk air purifier for office', 'cute backpacks for teen girls', 'car phone mount car phone holder', 'i phone xs small lens', '49mm to 82mm step up ring', 'apple certified ipad charging cables', 'micheal kors womens laptop briefcase', 'goody bags 1 day delivery', 'iphone 8 plus covers for women', 'clear case iphone 7 plus case', 'usb 3.1 gen 2 hub', 'mp3 player without voice recorder', '11 iphone pro screen protector', 'manubrios para bicicleta de ruta', 'blue light glasses for kids', 'cute iphone 7 phone case', 'usb wireless headset with microphone', '12 volt heater for trucks', 'samsung galaxy s9 case with stand', 'car mount for cell phone', 'logitech mx master 2s wireless mouse', 'hdmi coupler female to female', 'red iphone 11 pro max case', 'girls fanny pack under 5', 'iphone arm band men running', 'back drops for photo shoot', 'ear peace to talk to people', 'best stylus for tablet drawing', 'universal remote all element tv', 'car cell phone holder magnetic', 'tripod adapter for iphone 6s', 'beats solo 3 wireless headphones', 'cheap ear buds for android phones', 'phones for home with answering machine', 'bling clutch purses for women', 'iphone xs phone case clear', 'renogy 160w 12v solar panel', 'samsung galaxy s9 penguin case', 'large microfiber mirror cleaning cloth', '10k pearl settings without pearls', 'rechargeable 12v 7ah battery with charger', 'watch winders for automatic watches', 'iphone 11 pro case burgundy', 'small desks for small spaces', 'iphone 7 case white cockatiel', 'lcd display with video input', 'wii hdmi converter for smart tv', 'canon m50 mark ii full frame', 'phone cases for iphone xr', 'high sierra backpack with laptop compartment', 'samsung note 10 screen protector', 'kindle fire 10 cases and covers', 'best kids party bag items', 'onn tablet 7 inch case', 'galaxy s10+ case for women', 'leather dog collars for large dogs', '3.5 to rca audio cable', 'power cord without surge protector', 'samsung galaxy a10e case green', 'tech21 case for iphone 8 plus', 'plantronics wireless earbuds for running', 'men snow gloves with wrist guard', 'the little prince toy fox', 'ring light 18 inch without stand', '$25 ceiling fan without lights', '3 ring day planner pad', 'olixar ultra-thin iphone xr case', 'canon g7x mark ii monopod', 'usb to usb b cable', 'ryobi 18v hand vacuum attachments', 'xyzal allergy 24 hour 110 tablets', 'sling backpack purse for women kavu', 'balcony bar table for railings', 'japanese soup bowls and spoons set', 'go bowen electric kids go kart', 'octane curved theater seating 4 seats', 'iphone max hello kitty case', 'blackberry storm 2 case w/holster', 'ipad pro accessories 11 inch', 'things to put in resin', 'unlock sim card for iphone', 'things to get teens for christmas', 'airpods pro case cover zelda', 'universal travel adapter and converter', 'outdoor sound system with subwoofer', 'blink xt2 add on camera', 'portable battery pack ac outlet', 'automatic pill dispenser for elderly', '110 plug adapter without ground', 'power a grip for switch joycons', '902xl ink cartridges for hp printers', 'apple phone 8 plus unlocked', 'apple watch series 3 38mm band', 'x-ray iphone wallet with phone case', 'smar car accesoriea out side', 'love hope faith wall decor']

=== 7+ words ===
['intel i5 cpu laptop solid state hardrive', 'samsung usb type c cable fast charging', 'I want a google chromebook, that converts to a tablet, and it has to have a full size keyboard. ', 'I want a replacement chrome book with a touch screen. So really it would be an upgrade. I want a large screen and a good memory ', 'external storage for new android connection phones', '.625 width 20 gal metal strapping without holes', '1 white fancy box without a lid in living room', '1 day shipping fidgets not from china', 'samsung galaxy s9 gold cornered trunk case', '#i may not look like diesel decals', '1 bluetooth earphone with mic that will not fall out', 'bucket with hole in it pencil holder', '$1 million that look real but that is not it', 'warning does not play well with liberals sign', 'apple usb audio adapter with 3.5mm speaker/headphone', 'The laptop I would like would be a sleek, silver Apple Macbook Pro.', 'sony handycam fdr-ax53 4k ultra hd kit', 'cable matters usb to usb extension cable usb 3.0', 'akaso brave 4 4k remote control 2.4g', "I want a laptop that allows me to play some older games, surf the internet, and watch dvd's and blu-ray disks. ", '10 frame medium hive box without frames', 'pilot computer pens for touch screen for ipad', 'usb c to 3.5 mm headphone jack adapter', 'I would choose a medium weight fleece jacket with a hood.  I would choose a black colored jacket.', 'set it and forget it dual dash cam with super capacitor', 'samsung galaxy a10 e yellow silicon case', 'camping without beer is just sitting in the woods', '$15 fidget pack without the pea poppet', 'kawaii japanese strawberry milk drink bottle phone case', 'electric wheel chair with remote for caregiver', '2 line cordless phone without answering machine', '10 old boys motorcycle without training wheels', 'usb 3.0 type a to micro a', 'best white noise machine for sleeping adults', 'best air mattresses to blow your guests away', 'trail cameras with night vision motion activated waterproof', '100 foot led cuttable light without plug', 'workout leggings for women 90 degrees butt lifting', 'magnet phone case for samsung galaxy note 10 plus', 'nature made folic acid 400 mcg. tablets 250 ct', 'wireless outdoor security camera system battery operated', 'old english scratch cover for dark woods', 'dewalt 8v max cordless screwdriver kit, gyroscopic', 'table top music stand for sheet music', 'a day without video games is like', 'cordless phone without answering machine 3 handsets', 'hp ink 962xl black and color combo pack', 'cell phone card holder iphone 7 plus', "monopoly five nights at freddy's board game", 'atlantic furniture concord platform urban bed drawers', 'how to buy a business without being had', 'I would purchase the newest macbook pro with high storage capacity', 'clean zone cpap cleaner and sanitizing machine', 'A laptop with enough power to play 4K videos and run photoshop easily.', 'skins for a 15.6 laptop white tiger', '(can not use in the usa) european 220voltage hair tools', 'i would be buying an asus laptop or another brand of similar quality.', 'battery operated led light strip with remote', '16gb usb 3.0 flash drive 5 pack', 'mouse gaming for laptop asus rog zephyrus m15 compatible', 'body camera with audio recording wearable necklace', 'iphone 6s plus case full body protection', 'charging cord for norelco cordless electric razor s series', 'best gifts for 19 year old boys', 'disco duro para la xbox 360 fat', 'samsung note 9 privacy screen protector tempered glass', 'iphone xs wallet case compatible with wireless charging', 'note 20 ultra case credit card holder', 'xiaomi mi 9t pro phone tempered screen protector', 'cell phone protective screen cover samsung galaxy a6', 'fire tv stick 4k bundle with eco. (3rd gen)', 'charger for iphone 11 apple watch and airpods', 'Thin, lightweight but also waterproof and looks good. Hood not essential. ', 'from hdmi to screen display port bidirectional', 'guns make me happy you not so much', 'I would choose an upper end laptop with high specifcations, so that it will last for a number of years', 'petsafe smart feed automatic dog and cat feeder', 'food scales digital weight grams and oz', 'I would choose a laptop with a good screen, large RAM, great processor, and a good video card.', 'keep the earth clean its not uranus', 'best educational toys for 2 year old', 'charge car battery from the inside of car', 'led lights for bedroom without plug in', 'my dog makes me happy car magnets and decals', '05 vw passat window regulator without motor set', 'computer lap desk for laptop for bed', 'ssd hard drive docking station usb 2.0', '(pvc not wood) peel and stick banding', 'universal tv stand for 55 inch tv', 'I would buy a baubax travel jacket since I love all the pockets.', 'usb c to usb adapter thunderbolt 3 to usb 3.0', '1 hp garbage disposal without power cord', 'jeep 4.0 main and rod bearings .010', 'vintage phone game case for iphone xr', 'thinkpad p52 workstation laptop - windows 10 pro', '10 x 50 marine binoculars without range finder', 'lightning to usb a cable 1 ft', '08 tundra chrome tailgate handle without camera', 'I want to buy a laptop that has a lot of features, and is of good quality.', 'phone cases for iphone 11 pro max']

In [5]:
electronics_examples_with_source = electronics_examples.merge(
    shopping_queries_dataset_sources, on='query_id', how='left'
)
print(electronics_examples_with_source['source'].value_counts())

NameError: name 'electronics_examples' is not defined

In [33]:
# quick eyeball before deciding
unique_queries_check = electronics_examples_with_source.drop_duplicates(subset='query_id')
print(unique_queries_check[unique_queries_check['source']=='parse_pattern']['query'].sample(10, random_state=1).to_list())
print(unique_queries_check[unique_queries_check['source']=='nlqec']['query'].sample(10, random_state=1).to_list())

['bose lifestyle', 'xbox one final fantasy x', 'star plug in night light', 'ideapad slim 7', 'alexa cube remote control', 'noristudio sticker', 'pound fitness sticks', 'yellow and grey wall decor', 'xlr splitter 2 female 1 male', 'mobile printers for travel']
['The laptop should be a windows laptop. Light with powerful processor and good memory ', 'One with an SSD drive, good RAM, fast processor, and a 15 screen, lightweight but ideally with a built in DVD/CD drive', 'Portable, touch-screen, with a pen, high resolution display, good speakers. ', 'One that’s fast, reliable and has a good processor. I’d ideally like it to be light-weight too so that I can easily transport it.', 'Thin, lightweight but also waterproof and looks good. Hood not essential. ', 'I would buy the exact same laptop that I have now. I would get another Apple Macbook Air.', 'Not sure. Maybe a a standard size (15 or 17??) screen middle of the range laptop that is either black or purple. It might be a Dell or Acer ', 'I would buy an apple mac book air as they are light fast and easy to use', 'I want to buy a laptop that is touchscreen and has a long battery time. I also want it to be sleek and lightweight.', 'I would choose something small and lightweight, maybe a chromebook,']

In [34]:
training_pool_sources = ['other']  # extend with 'parse_pattern'/'nlqec' if the check above shows they're normal queries

training_pool = electronics_examples_with_source[
    electronics_examples_with_source['source'].isin(training_pool_sources)
].drop_duplicates(subset='query_id')[['query_id', 'query']]

training_pool['query_length'] = training_pool['query'].str.split().str.len()
print(len(training_pool), "candidate queries for the 500")
print(training_pool['query_length'].describe())

16418 candidate queries for the 500
count    16418.000000
mean         3.434219
std          1.481515
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         12.000000
Name: query_length, dtype: float64

In [36]:
training_pool_sources = ['other', 'parse_pattern']

training_pool = electronics_examples_with_source[
    electronics_examples_with_source['source'].isin(training_pool_sources)
].drop_duplicates(subset='query_id')[['query_id', 'query']]

training_pool['query_length'] = training_pool['query'].str.split().str.len()
print(len(training_pool), "candidate queries for the 500")
print(training_pool['query_length'].describe())

17058 candidate queries for the 500
count    17058.000000
mean         3.455153
std          1.486453
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max         12.000000
Name: query_length, dtype: float64

In [37]:
def bucket(n):
    if n <= 2:
        return '1-2'
    elif n <= 4:
        return '3-4'
    elif n <= 6:
        return '5-6'
    else:
        return '7+'

training_pool['length_bucket'] = training_pool['query_length'].apply(bucket)
bucket_counts = training_pool['length_bucket'].value_counts()
print(bucket_counts)
print((bucket_counts / len(training_pool) * 100).round(1))

length_bucket
3-4    8579
1-2    4804
5-6    3086
7+      589
Name: count, dtype: int64
length_bucket
3-4    50.3
1-2    28.2
5-6    18.1
7+      3.5
Name: count, dtype: float64

In [38]:
sample_sizes = {'1-2': 90, '3-4': 230, '5-6': 110, '7+': 70}

samples = []
for bucket_name, n in sample_sizes.items():
    bucket_pool = training_pool[training_pool['length_bucket'] == bucket_name]
    samples.append(bucket_pool.sample(n, random_state=42))

labeling_set = pd.concat(samples).reset_index(drop=True)
print(len(labeling_set))
print(labeling_set['length_bucket'].value_counts())

labeling_set.to_csv('classifier_labeling_set_500.csv', index=False)

500
length_bucket
3-4    230
5-6    110
1-2     90
7+      70
Name: count, dtype: int64

In [39]:
suspect_queries = ['belt', 'pa1', "amazoncom'", 'mail baskets', 'can crusher', 
                    'pokemon egg', 'hookah flavors', 'lockpicks kit', 
                    'lawn trencher', "mar'villa"]

for q in suspect_queries:
    match = training_pool[training_pool['query'] == q]
    if match.empty:
        continue
    qid = match['query_id'].iloc[0]
    rows = electronics_examples_with_source[electronics_examples_with_source['query_id'] == qid]
    merged = rows.merge(electronics_products[['product_id', 'product_title']], on='product_id', how='left')
    print(f"\n=== {q!r} ===")
    print(merged[['esci_label', 'product_title']].to_string(index=False))

=== 'belt' ===
esci_label                                                                                                                                    product_title
         E G-Run Hydration Running Belt with Bottles - Water Belts for Woman and Men - iPhone Belt for Any Phone Size - Fuel Marathon Race Pack for Runners

=== 'pa1' ===
esci_label                                                              product_title
         E               XP-PEN PA1 Battery-Free Stylus only Deco Pro Graphics Tablet
         E                    SNOM PA1 Public Address IP Phone Paging System (Latest)
         I Snom SNO-D715 Professional Sip Desk Telephone Voip Phone and Device, Black

=== "amazoncom'" ===
esci_label                                          product_title
         I              Apple AirPods with Wireless Charging Case
         E App Store & iTunes Surprise Gift Card- E-mail Delivery

=== 'mail baskets' ===
esci_label                                                                                                                                                                       product_title
         E Small Storage Basket Soft Felt Collapsible Baskets Storage Bins for Cellphone Earphone Chargers Cables Make Up Shelf Fabric Drawers Storage Baskets Cute Storage Baskets Light Gray

=== 'can crusher' ===
esci_label                                                                                                                      product_title
         E Ram-Pro 12 oz Aluminum Can Crusher & Bottle Opener | Heavy Duty Metal Wall Mounted Soda Beer Smasher – Eco-Friendly Recycling Tool
         E                                                                    ESKONI Can-ram Aluminum Can Crusher Crush 10 Cans in 10 Seconds

=== 'pokemon egg' ===
esci_label                                                                                                                                                                                     product_title
         I Steps Counter Compatible for Pokemon Go Walker, Poke Ball Plus Pokemon go Pedometer, Smart Watch, Two Phone Shaker, Phone Swing, Gotcha 2, Pokemon Brush, Automatic Egg Hatcher Earn Steps by USB
         I               Orzero Steps Counter Accessories Compatible for Pokemon Go Cellphone Pedometer, (USB Cable) (Easy Installation) (Mute Version) (Support 2 Phones) Quick Steps Earning Device- Black

=== 'hookah flavors' ===
esci_label                                                                                                                                                                           product_title
         I Charcoal Tablets For Incense– Quick Light Charcoal Tablets – Charcoal Disk Lights – 33 mm Resin Burner Rolls – Pack of 100 Coal Briquettes – Charcoal Burner - Instant Fire Coal Tablet

=== 'lockpicks kit' ===
esci_label                                                                                                                                                                                        product_title
         S             Syntus Precision Screwdriver Set, 63 in 1 with 57 Bits Screwdriver Kit, Magnetic Driver Electronics Repair Tool Kit for iPhone, Tablet, Macbook, Xbox, Cellphone, PC, Game Console, Blue
         E Precision Screwdriver Kit, XOOL 80 in 1 Professional Electronics Repair Tool Magnetic Driver Kit with Flexible Shaft, Extension Rod for Computer, Mobile Phone, Smartphone, Game Console, PC, Tablet
         E                                                                                                                      iFixit Pro Tech Toolkit - Electronics, Smartphone, Computer & Tablet Repair Kit

=== 'lawn trencher' ===
esci_label                                                                                 product_title
         S      Ryobi ONE+ 9 in. 18-Volt Lithium-Ion Cordless Edger, 1.3 Ah Battery and Charger Included
         S Ryobi P2300A ONE+ 9 in. 18-Volt Lithium-Ion Cordless Edger - Battery and Charger Not Included

=== "mar'villa" ===
esci_label                                                                                                                                                                                    product_title
         E Mar'villa UV-C Phone Sanitizer & Wireless Charging Stand - Portable UV Light Cell Phone Sterilizer - Kills 99.99% of Germs and Viruses - Perfect for Disinfecting at Work & Home (Glacier White)

In [40]:
# a query only counts as "electronics" if it has at least one Exact or Substitute
# labeled product within the electronics catalog — not just any judged product
positive_labels = ['E', 'S']

electronics_query_ids = electronics_examples_with_source[
    electronics_examples_with_source['esci_label'].isin(positive_labels)
]['query_id'].unique()

training_pool_v2 = electronics_examples_with_source[
    (electronics_examples_with_source['query_id'].isin(electronics_query_ids)) &
    (electronics_examples_with_source['source'].isin(['other', 'parse_pattern']))
].drop_duplicates(subset='query_id')[['query_id', 'query']].copy()

training_pool_v2['query_length'] = training_pool_v2['query'].str.split().str.len()
print(len(training_pool_v2))

15622

In [41]:
# 1. "ram" as a standalone word needs to require memory-context, not just any brand containing "Ram"
ram_context_pattern = r'\b\d+\s?(?:gb|tb|mb)\s*ram\b|\bram\s*\d+\s?(?:gb|tb|mb)\b|\bddr[345]\b'
# replace bare "ram" in electronics_keywords with this context-aware check instead

# 2. cordless outdoor power tools — a recurring leak across brands (Greenworks, Ryobi, MOCOHANA)
outdoor_tool_pattern = r'\b(?:edger|trimmer|chainsaw|lawn\s?mower|leaf\s?blower|hedge\s?trimmer|pole\s?saw|weed\s?wacker)\b'
outdoor_tool_mask = title_lower.str.contains(outdoor_tool_pattern, regex=True)

electronics_products = electronics_products[~outdoor_tool_mask].copy()
print(len(electronics_products))

C:\Users\chamo\AppData\Local\Temp\ipykernel_27072\3775437455.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  electronics_products = electronics_products[~outdoor_tool_mask].copy()

60664

In [42]:
electronics_ids = set(electronics_products['product_id'])
electronics_examples = shopping_queries_dataset_examples[
    (shopping_queries_dataset_examples['product_locale'] == 'us') &
    (shopping_queries_dataset_examples['product_id'].isin(electronics_ids))
]
print(electronics_examples['query'].nunique(), "distinct electronics queries")
print(len(electronics_examples), "electronics query-product judgment rows")
print(electronics_examples['esci_label'].value_counts())

17919 distinct electronics queries
122004 electronics query-product judgment rows
esci_label
E    83948
S    25595
I     8502
C     3959
Name: count, dtype: int64

In [43]:
electronics_examples_with_source = electronics_examples.merge(
    shopping_queries_dataset_sources, on='query_id', how='left'
)
print(electronics_examples_with_source['source'].value_counts())

source
other            112988
parse_pattern      3478
negations          3379
behavioral         1170
nlqec               989
Name: count, dtype: int64

In [44]:
positive_labels = ['E', 'S']

electronics_query_ids = electronics_examples_with_source[
    electronics_examples_with_source['esci_label'].isin(positive_labels)
]['query_id'].unique()

training_pool_v2 = electronics_examples_with_source[
    (electronics_examples_with_source['query_id'].isin(electronics_query_ids)) &
    (electronics_examples_with_source['source'].isin(['other', 'parse_pattern']))
].drop_duplicates(subset='query_id')[['query_id', 'query']].copy()

training_pool_v2['query_length'] = training_pool_v2['query'].str.split().str.len()
print(len(training_pool_v2))

15550

In [45]:
training_pool_v2['length_bucket'] = training_pool_v2['query_length'].apply(bucket)
print(training_pool_v2['length_bucket'].value_counts())

length_bucket
3-4    7829
1-2    4344
5-6    2839
7+      538
Name: count, dtype: int64

In [46]:
sample_sizes = {'1-2': 90, '3-4': 230, '5-6': 110, '7+': 70}

samples = []
for bucket_name, n in sample_sizes.items():
    bucket_pool = training_pool_v2[training_pool_v2['length_bucket'] == bucket_name]
    samples.append(bucket_pool.sample(n, random_state=42))

labeling_set_v2 = pd.concat(samples).reset_index(drop=True)
print(len(labeling_set_v2))
print(labeling_set_v2['length_bucket'].value_counts())

labeling_set_v2.to_csv('classifier_labeling_set_500_v2.csv', index=False)

500
length_bucket
3-4    230
5-6    110
1-2     90
7+      70
Name: count, dtype: int64